// Generated by scripts/generate_ui_contracts.py.
// Do not edit this file manually.

export interface AutomationHealthDto {
  status?: "healthy" | "degraded" | "inconclusive";
  reasons?: string[];
  trigger_requested?: boolean;
  trigger_loaded?: boolean;
  trigger_applied?: boolean;
  extension_host_log_present?: boolean;
  extension_host_log_found?: boolean;
  extension_host_output_present?: boolean;
  target_stream_present?: boolean;
  target_activation_count?: number;
  failed_scenarios?: string[];
  extra_trigger_failures?: string[];
  extra_trigger_failure_count?: number;
  skipped_scenarios?: string[];
}

export interface LogHealthDto {
  extension_host_log_found?: boolean;
  extension_host_output_present?: boolean;
  target_extension_log_entries?: number;
  total_activation_entries?: number;
}

export interface AttributionSummaryDto {
  target_activation_count?: number;
  strong_target_file_event_count?: number;
  strong_target_network_event_count?: number;
  correlated_only_event_count?: number;
  target_background_activation_count?: number;
  competing_extension_event_count?: number;
  ui_blocker_count?: number;
}

export interface RiskSummaryDto {
  total_signals?: number;
  critical?: number;
  high?: number;
  medium?: number;
  low?: number;
  categories?: string[];
}

export interface CoverageSummaryDto {
  covered?: number;
  partial?: number;
  missing?: number;
  attempted?: number;
  verified?: number;
  covered_capabilities?: string[];
  partial_capabilities?: string[];
  missing_capabilities?: string[];
  attempted_capabilities?: string[];
  verified_capabilities?: string[];
}

export interface CoverageCapabilityDto {
  capability: string;
  status: string;
  track?: string;
  source?: string;
  support_status?: string;
  verification_status?: string;
  selected_scenarios?: string[];
  supported_scenarios?: string[];
  notes?: string;
  is_active?: boolean;
  selected?: boolean;
  attempted?: boolean;
  verified?: boolean;
}

export interface CoverageTrackDto {
  source?: string;
  selected_scenarios?: string[];
  summary?: CoverageSummaryDto;
  matrix?: CoverageCapabilityDto[];
}

export interface CoverageTracksDto {
  official?: CoverageTrackDto;
  heuristic?: CoverageTrackDto;
}

export interface EventCoverageDto {
  track?: string;
  declared?: number;
  verified?: number;
  attempted_only?: number;
  failed?: number;
  blocked?: number;
  unresolved?: number;
  declared_events?: string[];
}

export interface LogStreamsDto {
  target_extension_host?: LogStreamEntryDto[];
  other_extension_host?: LogStreamEntryDto[];
  automation?: LogStreamEntryDto[];
  ui_blockers?: LogStreamEntryDto[];
}

export interface AnalysisBundleDto {
  activation_report: ActivationReportDto;
  detection_report: DetectionReportDto;
}

export interface ReportBundleDto {
  activation_report: ActivationReportDto;
  detection_report: DetectionReportDto;
  static_report?: StaticAnalysisReportDto | null;
}

export interface ReportListItemDto {
  filename: string;
  size_bytes: number;
  modified: number;
}

export interface ActivationEntryDto {
  extension_id: string;
  activation_event?: string;
  duration_ms?: number | null;
  timestamp?: string;
  success?: boolean;
  source?: string;
  marker_type?: string;
}

export type AdversaryClassDto = "A1" | "A2" | "A3" | "A4" | "A5" | "A6" | "A7" | "A8";

export type ConfidenceDto = "high" | "medium" | "low";

export interface DetectionFindingDto {
  id?: string;
  rule_id: string;
  rule_version: string;
  rule_lifecycle: RuleLifecycleDto;
  categories: string[];
  severity: SeverityDto;
  confidence: ConfidenceDto;
  title: string;
  description: string;
  evidence?: EvidenceRefDto[];
  adversary_class?: AdversaryClassDto | null;
  mitigation_hint?: string | null;
}

export interface DetectionReportDto {
  schema_version?: "1";
  activation_report_ref: string;
  analyzed_extension: ExtensionIdentityDto;
  findings?: DetectionFindingDto[];
  verdict: VerdictDto;
  verdict_rationale: string;
  rules_executed?: RuleExecutionRecordDto[];
  generated_at?: string;
}

export interface EvidenceRefDto {
  type: string;
  event_id: string;
  summary?: string | null;
}

export interface ExtensionIdentityDto {
  publisher: string;
  name: string;
  version: string;
}

export interface RunningExtensionDto {
  extension_id: string;
  name?: string;
  activation_time_ms?: number | null;
  status?: string;
}

export interface EvidenceEventDto {
  event_id: string;
  kind: string;
  timestamp?: string;
  rel_time_s?: number | null;
  collector?: string;
  actor?: string;
  scenario_name?: string;
  extension_id?: string;
  activation_event?: string;
  operation?: string;
  protocol?: string;
  host?: string;
  path?: string;
  destination_ip?: string;
  destination_port?: number | null;
  attribution_status?: string;
  attribution_basis?: string;
  attribution_confidence?: number;
  is_target_extension_event?: boolean;
  noise_reason?: string;
  artifact_class?: string;
  sensitive?: boolean;
  summary?: string;
  raw_context?: NetworkRawContextDto | FileRawContextDto | ProcessRawContextDto | ScenarioRawContextDto | ActivationRawContextDto | UiBlockerRawContextDto | OutputChannelRawContextDto;
}

export interface EvidenceLinkDto {
  from_event_id: string;
  to_event_id: string;
  link_type: string;
  confidence: number;
  reason: string;
}

export interface NetworkEventDto {
  timestamp?: string;
  rel_time_s?: number | null;
  protocol?: string;
  event_type?: string;
  source_ip?: string;
  destination_ip?: string;
  destination_port?: number | null;
  host?: string;
  path?: string;
  http_method?: string;
  http_status_code?: number | null;
  http_content_type?: string;
  request_body_sha256?: string;
  request_body_preview?: string;
  request_body_truncated?: boolean;
  response_body_sha256?: string;
  response_body_preview?: string;
  response_body_truncated?: boolean;
  related_extension_id?: string;
  related_activation_event?: string;
  attribution_status?: string;
  attribution_basis?: string;
  attribution_confidence?: number;
  is_target_extension_event?: boolean;
  noise_reason?: string;
  summary?: string;
}

export interface FileEventDto {
  timestamp?: string;
  rel_time_s?: number | null;
  operation?: string;
  path?: string;
  secondary_path?: string;
  source?: string;
  observer?: string;
  pid?: number | null;
  scenario_name?: string;
  related_extension_id?: string;
  related_activation_event?: string;
  attribution_status?: string;
  attribution_basis?: string;
  attribution_confidence?: number;
  is_target_extension_event?: boolean;
  noise_reason?: string;
  artifact_class?: string;
  flags?: string;
  sensitive?: boolean;
  summary?: string;
}

export interface ProcessEventDto {
  timestamp?: string;
  rel_time_s?: number | null;
  pid: number;
  ppid?: number | null;
  operation?: string;
  command?: string;
  arguments_preview?: string;
  cwd?: string;
  related_extension_id?: string;
  related_activation_event?: string;
  attribution_status?: string;
  attribution_basis?: string;
  attribution_confidence?: number;
  is_target_extension_event?: boolean;
  summary?: string;
}

export interface OutputSignalEventDto {
  timestamp?: string;
  rel_time_s?: number | null;
  channel?: string;
  text?: string;
  extension_id?: string;
  activation_event?: string;
  is_target_extension_event?: boolean;
  attribution_status?: string;
  attribution_basis?: string;
  summary?: string;
}

export interface NetworkRawContextDto {
  event_class?: "network";
  event_type?: string;
  source_ip?: string;
  path?: string;
  http_method?: string;
  http_status_code?: number | null;
  http_content_type?: string;
  request_body_sha256?: string;
  request_body_preview?: string;
  request_body_truncated?: boolean;
  response_body_sha256?: string;
  response_body_preview?: string;
  response_body_truncated?: boolean;
}

export interface FileRawContextDto {
  event_class?: "file";
  secondary_path?: string;
  flags?: string;
  observer?: string;
  source?: string;
  pid?: number | null;
}

export interface ProcessRawContextDto {
  event_class?: "process";
  pid: number;
  ppid?: number | null;
  command?: string;
  arguments_preview?: string;
  cwd?: string;
}

export interface ScenarioRawContextDto {
  event_class?: "scenario";
  status?: string;
  started_at?: number;
  ended_at?: number;
}

export interface ActivationRawContextDto {
  event_class?: "activation";
  success?: boolean;
  duration_ms?: number | null;
  source?: string;
}

export interface UiBlockerRawContextDto {
  event_class?: "ui_blocker";
  status?: string;
  stream?: string;
}

export interface OutputChannelRawContextDto {
  event_class?: "output_channel_appendline";
  channel?: string;
  text?: string;
}

export interface RuleExecutionRecordDto {
  rule_id: string;
  rule_version: string;
  lifecycle: RuleLifecycleDto;
  status: RuleExecutionStatusDto;
  finding_ids?: string[];
  error_detail?: string | null;
}

export type RuleExecutionStatusDto = "fired" | "silent" | "error";

export type RuleLifecycleDto = "draft" | "fixture_validated" | "smoke_validated" | "production" | "deprecated";

export interface ScenarioTraceDto {
  name: string;
  started_at: number;
  ended_at?: number;
  status?: string;
  failure_reason_code?: string;
  error_detail?: string;
}

export interface SkippedScenarioRecordDto {
  name: string;
  reason_code: string;
  detail?: string;
}

export type SeverityDto = "critical" | "high" | "medium" | "low" | "info";

export interface StimulusPassDto {
  pass_id: string;
  label: string;
  order: number;
  started_at: number;
  ended_at?: number;
  status?: string;
  trigger_method?: string;
}

export interface PrerequisiteResultDto {
  prerequisite_id: string;
  key: string;
  label: string;
  status?: string;
  materializer?: string;
  pass_name?: string;
  attempt_ids?: string[];
  detail?: string;
  reason_code?: string;
  resolved_targets?: Record<string, unknown>;
}

export interface EventAttemptDto {
  attempt_id: string;
  declared_event: string;
  activation_event: string;
  event_family: string;
  event_value?: string;
  track?: string;
  selected_by?: string;
  selection_reasons?: string[];
  pass_name?: string;
  backfill_pass_name?: string;
  prerequisite_keys?: string[];
  verification_contract?: string[];
  trigger_method?: string;
  fallback_trigger_method?: string;
  executor_action?: string;
  backfill_executor_action?: string;
  legacy_scenarios?: string[];
  capability_tags?: string[];
  status?: string;
  trigger_method_used?: string;
  attempted_passes?: string[];
  evidence?: string[];
  verification_status?: string;
  failure_reason_code?: string;
  blocked_reason_code?: string;
  result_details?: string;
  official?: boolean;
  heuristic?: boolean;
  ui_path?: string;
  harness_fallback?: string;
  confirmation_source?: string;
}

export interface LogStreamEntryDto {
  timestamp?: string;
  rel_time_s?: number | null;
  stream?: string;
  kind?: string;
  message?: string;
  extension_id?: string;
  activation_event?: string;
  scenario_name?: string;
  status?: string;
  is_target_extension?: boolean;
}

export interface RiskSignalDto {
  signal_id: string;
  category: string;
  severity: string;
  confidence: number;
  confidence_tier?: string;
  evidence_event_ids?: string[];
  summary?: string;
  details?: Record<string, unknown>;
}

export type VerdictDto = "malicious" | "suspicious" | "clean_with_notes" | "clean" | "inconclusive";

export interface ActivationReportMetadataDto {
  filename: string;
}

export interface ActivationReportDto {
  schema_version?: string;
  report_version: number;
  target_extension_expected: string;
  automation_health: AutomationHealthDto;
  signal_summary: Record<string, unknown>;
  summary: Record<string, unknown>;
  scenario_traces: ScenarioTraceDto[];
  skipped_scenarios?: SkippedScenarioRecordDto[];
  evidence_events: EvidenceEventDto[];
  network_events: NetworkEventDto[];
  file_events: FileEventDto[];
  process_events?: ProcessEventDto[];
  log_streams: LogStreamsDto;
  target_extension_observed?: boolean;
  trigger_plan_requested?: boolean;
  trigger_plan_loaded?: boolean;
  trigger_plan_applied?: boolean;
  trigger_plan_path?: string;
  trigger_execution_mode?: string;
  requested_scenarios?: string[];
  failed_scenarios?: string[];
  extra_trigger_failures?: string[];
  verification_gap?: number;
  heuristic_verification_gap?: number;
  run_quality?: string;
  run_quality_reasons?: string[];
  run_quality_reason_partition?: Record<string, string[]>;
  log_health?: LogHealthDto;
  attribution_summary?: AttributionSummaryDto;
  risk_signals?: RiskSignalDto[];
  risk_summary?: RiskSummaryDto;
  attempted_capabilities?: string[];
  verified_capabilities?: string[];
  official_attempted_capabilities?: string[];
  official_verified_capabilities?: string[];
  heuristic_attempted_capabilities?: string[];
  heuristic_verified_capabilities?: string[];
  network_capture_error?: string;
  file_capture_error?: string;
  file_capture_diagnostics?: Record<string, unknown>;
  activated?: ActivationEntryDto[];
  running_extensions?: RunningExtensionDto[];
  stimulus_passes?: StimulusPassDto[];
  prerequisite_results?: PrerequisiteResultDto[];
  event_attempts?: EventAttemptDto[];
  evidence_links?: EvidenceLinkDto[];
  network_summary?: Record<string, unknown>;
  file_summary?: Record<string, unknown>;
  coverage_summary?: CoverageSummaryDto;
  coverage_matrix?: CoverageCapabilityDto[];
  coverage_tracks?: CoverageTracksDto;
  official_event_coverage?: EventCoverageDto;
  heuristic_workflow_coverage?: EventCoverageDto;
  extension_host_output_lines?: number;
  extension_host_output?: string;
  log_file?: string;
  output_signal_events?: OutputSignalEventDto[];
  activation_discovery_strategy_outcomes?: Record<string, string>;
  runner_exit_code?: number | null;
  runner_status?: "success" | "error" | "unknown";
  executor_fingerprint?: Record<string, string>;
  vsix_sha256?: string;
  target_extension_id?: string;
  monitoring_start?: number;
  monitoring_end?: number;
  scenarios_run?: string[];
  harness_handshake_required?: boolean;
  _metadata?: ActivationReportMetadataDto | null;
}

export interface StaticReportArtifactDto {
  filename: string;
  modified: number;
  static_report: StaticAnalysisReportDto;
}

export interface MarketplaceExtensionDto {
  publisher: string;
  name: string;
  version: string;
  displayName: string;
  description: string;
  installs: number;
  rating: number;
}

export interface OfflineExtensionDto {
  publisher: string;
  name: string;
  version: string;
  displayName: string;
  description: string;
  filename: string;
  size_bytes: number;
  already_ingested: boolean;
}

export interface VsixExtractionMetricsDto {
  file_count: number;
  uncompressed_size: number;
  compressed_size: number;
  compression_ratio: number;
  rejected_entry_count: number;
}

export interface ExecutorPreferencesResponseDto {
  dynamic_analysis_enabled: boolean;
}

export interface ExecutorPreferencesUpdateRequestDto {
  dynamic_analysis_enabled: boolean;
  updated_by?: string | null;
}

export interface SystemMetricDto {
  label: string;
  value: string;
}

export interface SystemServiceHealthDto {
  id: string;
  name: string;
  health: "ok" | "degraded" | "down" | "unknown";
  status: string;
  detail: string;
  source: string;
  metrics: SystemMetricDto[];
  observations: string[];
}

export interface SystemInventoryItemDto {
  label: string;
  value: string;
}

export interface SystemHealthResponseDto {
  observed_at: string;
  services: SystemServiceHealthDto[];
  inventory: SystemInventoryItemDto[];
}

export interface VsixThresholdBoundsDto {
  min_value: number;
  max_value: number;
}

export interface VsixThresholdsResponseDto {
  values: Record<string, number>;
  defaults: Record<string, number>;
  bounds: Record<string, VsixThresholdBoundsDto>;
  keys: string[];
}

export interface VsixThresholdsUpdateRequestDto {
  values?: Record<string, number>;
  updated_by?: string | null;
}

export interface VsixThresholdBreachDetail {
  error: "vsix_threshold_breach";
  breach_kind: "entry_count" | "uncompressed_size" | "compression_ratio";
  threshold_name: string;
  threshold_value: number;
  observed_value: number;
  message: string;
  publisher: string;
  name: string;
  version: string;
}

export interface MarketplaceDownloadResponseDto {
  status: string;
  publisher: string;
  name: string;
  version: string;
  extension_dir: string;
  db_id?: number | null;
  message: string;
  vsix_metrics?: VsixExtractionMetricsDto | null;
}

export interface AnalyzeJobStepDto {
  name: string;
  status: string;
  message: string;
  error_code?: string | null;
  progress?: AnalyzeJobStepProgressDto | null;
}

export interface AnalyzeJobStepProgressDto {
  completed: number;
  total: number;
}

export interface AnalyzeJobStatusDto {
  job_id: string;
  status: string;
  publisher: string;
  name: string;
  version: string;
  scenario?: string | null;
  current_step?: string | null;
  message: string;
  steps?: AnalyzeJobStepDto[];
  report_path?: string | null;
  install_output?: string | null;
  automation_output?: string | null;
  error_detail?: string | null;
  error_code?: string | null;
  created_at: number;
  started_at?: number | null;
  finished_at?: number | null;
  updated_at: number;
  detection_report?: DetectionReportDto | null;
  report_error?: string | null;
  static_report_path?: string | null;
  static_report?: StaticAnalysisReportDto | null;
}

export type StaticGateDecisionDto = "allow" | "warn" | "block" | "inconclusive";

export interface StaticGateOutcomeDto {
  decision: StaticGateDecisionDto;
  blocked_by?: string[];
  warned_by?: string[];
  inconclusive_reasons?: string[];
  allow_reason?: string | null;
  decided_at?: string;
}

export interface StaticEvidenceRefDto {
  type: "manifest" | "source_file" | "binary_file" | "lockfile" | "dependency";
  relative_path: string;
  line_number?: number | null;
  snippet?: string | null;
  tool: string;
  rule_match_id?: string | null;
}

export interface StaticReachabilityUnresolvedReferenceDto {
  source_path: string;
  line_number: number;
  edge_kind: "manifest" | "import" | "export" | "require" | "dynamic_import" | "require_resolve" | "source_map" | "path_loader" | "native_loader";
  expression: string;
}

export interface StaticReachabilitySummaryDto {
  roots?: string[];
  nodes_reached?: number;
  edges_resolved?: number;
  bytes_read?: number;
  unresolved_count?: number;
  unresolved_references?: StaticReachabilityUnresolvedReferenceDto[];
  limit_reasons?: ("node_cap" | "edge_cap" | "byte_cap" | "depth_cap" | "read_error" | "parse_error")[];
}

export interface StaticFindingDeduplicationRecordDto {
  rule_id: string;
  rule_version: string;
  reason: "vendor_echo" | "source_map_echo";
  canonical_path: string;
  canonical_line_number?: number | null;
  duplicate_path: string;
  duplicate_line_number?: number | null;
  evidence_fingerprint: string;
}

export interface StaticArtifactInventoryEntryDto {
  relative_path: string;
  role: "manifest" | "first_party_runtime" | "dependency_runtime" | "documentation" | "license" | "test" | "asset" | "source_map" | "configuration" | "native" | "wasm" | "archive" | "unknown";
  format: "text" | "png" | "jpeg" | "gif" | "webp" | "font" | "sqlite" | "zip" | "gzip" | "7z" | "rar" | "tar" | "pe" | "elf" | "mach_o" | "wasm" | "opaque_binary" | "unknown";
  size_bytes: number;
  header_sha256?: string | null;
  header_bytes_read?: number;
  extension_header_match?: boolean | null;
  dependency_owner?: string | null;
  is_vendor?: boolean;
  is_minified?: boolean;
  entrypoint_reachability?: "direct" | "transitive" | "none" | "unknown";
  reachability_parent?: string | null;
  reachability_edge_kind?: "manifest" | "import" | "export" | "require" | "dynamic_import" | "require_resolve" | "source_map" | "path_loader" | "native_loader" | null;
  reachability_confidence?: "literal" | "heuristic" | null;
  disposition: "deep_scan" | "inventory_only" | "skipped";
  disposition_reasons: ("first_party_runtime" | "direct_manifest_entrypoint" | "transitive_entrypoint_reachable" | "heuristic_loader_reachable" | "inhouse_finding_evidence" | "format_extension_mismatch" | "dependency_inventory_only" | "vendor_inventory_only" | "minified_inventory_only" | "non_runtime_artifact" | "unsupported_format" | "target_too_large" | "read_error" | "deep_scan_target_cap")[];
}

export interface StaticDetectionFindingDto {
  id?: string;
  rule_id: string;
  rule_version: string;
  rule_lifecycle: RuleLifecycleDto;
  categories: string[];
  severity: SeverityDto;
  confidence: ConfidenceDto;
  title: string;
  description: string;
  evidence?: StaticEvidenceRefDto[];
  adversary_class?: AdversaryClassDto | null;
  mitigation_hint?: string | null;
}

export interface StaticToolExecutionRecordDto {
  tool: "inhouse" | "semgrep" | "yara" | "trivy";
  version: string;
  rules_loaded: number;
  findings_emitted: number;
  duration_ms: number;
  status?: "ok" | "partial" | "error" | "timeout";
  error_count?: number;
  errored_rule_ids?: string[];
  coverage?: StaticScanCoverageDto;
  db_freshness_days?: number | null;
}

export interface StaticScanCoverageDto {
  files_discovered?: number;
  files_selected?: number;
  files_eligible?: number;
  files_scanned?: number;
  files_parsed?: number;
  files_skipped_by_reason?: Record<string, number>;
  skipped_paths_by_reason?: Record<string, string[]>;
  bytes_considered?: number;
  bytes_read?: number;
  manifest_status?: "parsed" | "missing" | "malformed" | "too_large" | "unreadable" | "non_object";
  critical_entrypoints?: string[];
  critical_entrypoints_parsed?: string[];
  file_cap_reached?: boolean;
  finding_cap_reached?: boolean;
  unsupported_formats?: Record<string, number>;
  structural_fallback_files?: number;
  structural_fallback_paths?: string[];
  coverage_reasons?: ("file_cap" | "target_too_large" | "text_truncated" | "undecodable" | "unsupported_suffix" | "parser_error" | "manifest_missing" | "manifest_malformed" | "manifest_too_large" | "critical_entrypoint_missing" | "critical_entrypoint_unparsed" | "rule_timeout" | "tool_timeout" | "tool_error" | "finding_cap" | "budget_stop" | "excluded_inventory_only" | "deep_scan_target_cap" | "reachability_node_cap" | "reachability_edge_cap" | "reachability_byte_cap" | "reachability_depth_cap" | "reachability_read_error" | "reachability_parse_error")[];
}

export interface StaticSeverityCountsDto {
  critical?: number;
  high?: number;
  medium?: number;
  low?: number;
  info?: number;
}

export interface StaticDetectionReportDto {
  schema_version?: "2";
  findings?: StaticDetectionFindingDto[];
  tool_executions?: StaticToolExecutionRecordDto[];
  severity_counts?: StaticSeverityCountsDto;
  partial?: boolean;
  coverage?: StaticScanCoverageDto;
  artifact_inventory?: StaticArtifactInventoryEntryDto[];
  reachability?: StaticReachabilitySummaryDto;
  finding_deduplications?: StaticFindingDeduplicationRecordDto[];
  generated_at?: string;
  vsix_sha256?: string;
}

export interface StaticAnalysisReportDto {
  detection_report: StaticDetectionReportDto;
  gate_outcome: StaticGateOutcomeDto;
}
