// Generated by scripts/generate_ui_contracts.py.
// Do not edit this file manually.

export interface AutomationHealthDto {
  status?: "healthy" | "degraded" | "inconclusive";
  reasons?: string[];
  trigger_requested?: boolean;
  trigger_loaded?: boolean;
  trigger_applied?: boolean;
  extension_host_log_present?: boolean;
  extension_host_log_found?: boolean;
  extension_host_output_present?: boolean;
  target_stream_present?: boolean;
  target_activation_count?: number;
  failed_scenarios?: string[];
  extra_trigger_failures?: string[];
  extra_trigger_failure_count?: number;
  skipped_scenarios?: string[];
}

export interface LogHealthDto {
  extension_host_log_found?: boolean;
  extension_host_output_present?: boolean;
  target_extension_log_entries?: number;
  total_activation_entries?: number;
}

export interface AttributionSummaryDto {
  target_activation_count?: number;
  strong_target_file_event_count?: number;
  strong_target_network_event_count?: number;
  correlated_only_event_count?: number;
  background_activation_count?: number;
  competing_candidate_count?: number;
  ui_blocker_count?: number;
}

export interface RiskSummaryDto {
  total_signals?: number;
  critical?: number;
  high?: number;
  medium?: number;
  low?: number;
  categories?: string[];
}

export interface CoverageSummaryDto {
  covered?: number;
  partial?: number;
  missing?: number;
  attempted?: number;
  verified?: number;
  covered_capabilities?: string[];
  partial_capabilities?: string[];
  missing_capabilities?: string[];
  attempted_capabilities?: string[];
  verified_capabilities?: string[];
}

export interface CoverageCapabilityDto {
  capability: string;
  status: string;
  track?: string;
  source?: string;
  support_status?: string;
  verification_status?: string;
  selected_scenarios?: string[];
  supported_scenarios?: string[];
  notes?: string;
  is_active?: boolean;
  selected?: boolean;
  attempted?: boolean;
  verified?: boolean;
}

export interface CoverageTrackDto {
  source?: string;
  selected_scenarios?: string[];
  summary?: CoverageSummaryDto;
  matrix?: CoverageCapabilityDto[];
}

export interface CoverageTracksDto {
  official?: CoverageTrackDto;
  heuristic?: CoverageTrackDto;
}

export interface EventCoverageDto {
  track?: string;
  declared?: number;
  verified?: number;
  attempted_only?: number;
  failed?: number;
  blocked?: number;
  unresolved?: number;
  declared_events?: string[];
}

export interface LogStreamsDto {
  target_extension_host?: LogStreamEntryDto[];
  other_extension_host?: LogStreamEntryDto[];
  automation?: LogStreamEntryDto[];
  ui_blockers?: LogStreamEntryDto[];
}

export interface AnalysisBundleDto {
  activation_report: ActivationReportDto;
  detection_report: DetectionReportDto;
}

export interface ReportListItemDto {
  filename: string;
  size_bytes: number;
  modified: number;
}

export interface ActivationEntryDto {
  extension_id: string;
  activation_event?: string;
  duration_ms?: number | null;
  timestamp?: string;
  success?: boolean;
  source?: string;
  marker_type?: string;
}

export type AdversaryClassDto = "A1" | "A2" | "A3" | "A4" | "A5" | "A6" | "A7";

export type ConfidenceDto = "high" | "medium" | "low";

export interface DetectionFindingDto {
  id?: string;
  rule_id: string;
  rule_version: string;
  rule_lifecycle: RuleLifecycleDto;
  categories: string[];
  severity: SeverityDto;
  confidence: ConfidenceDto;
  title: string;
  description: string;
  evidence?: EvidenceRefDto[];
  adversary_class?: AdversaryClassDto | null;
  mitigation_hint?: string | null;
}

export interface DetectionReportDto {
  schema_version?: string;
  activation_report_ref: string;
  analyzed_extension: ExtensionIdentityDto;
  findings?: DetectionFindingDto[];
  verdict: VerdictDto;
  verdict_rationale: string;
  rules_executed?: RuleExecutionRecordDto[];
  generated_at?: string;
}

export interface EvidenceRefDto {
  type: string;
  event_id: string;
  summary?: string | null;
}

export interface ExtensionIdentityDto {
  publisher: string;
  name: string;
  version: string;
}

export interface RunningExtensionDto {
  extension_id: string;
  name?: string;
  activation_time_ms?: number | null;
  status?: string;
}

export interface EvidenceEventDto {
  event_id: string;
  kind: string;
  timestamp?: string;
  rel_time_s?: number | null;
  collector?: string;
  actor?: string;
  scenario_name?: string;
  extension_id?: string;
  activation_event?: string;
  operation?: string;
  protocol?: string;
  host?: string;
  path?: string;
  destination_ip?: string;
  destination_port?: number | null;
  attribution_status?: string;
  attribution_basis?: string;
  attribution_confidence?: number;
  is_target_extension_event?: boolean;
  noise_reason?: string;
  artifact_class?: string;
  sensitive?: boolean;
  summary?: string;
  raw_context?: Record<string, unknown>;
}

export interface EvidenceLinkDto {
  from_event_id: string;
  to_event_id: string;
  link_type: string;
  confidence: number;
  reason: string;
}

export interface NetworkEventDto {
  timestamp?: string;
  rel_time_s?: number | null;
  protocol?: string;
  event_type?: string;
  source_ip?: string;
  destination_ip?: string;
  destination_port?: number | null;
  host?: string;
  path?: string;
  http_method?: string;
  http_status_code?: number | null;
  http_content_type?: string;
  request_body_sha256?: string;
  request_body_preview?: string;
  request_body_truncated?: boolean;
  response_body_sha256?: string;
  response_body_preview?: string;
  response_body_truncated?: boolean;
  related_extension_id?: string;
  related_activation_event?: string;
  attribution_status?: string;
  attribution_basis?: string;
  attribution_confidence?: number;
  is_target_extension_event?: boolean;
  noise_reason?: string;
  summary?: string;
}

export interface FileEventDto {
  timestamp?: string;
  rel_time_s?: number | null;
  operation?: string;
  path?: string;
  secondary_path?: string;
  source?: string;
  observer?: string;
  scenario_name?: string;
  related_extension_id?: string;
  related_activation_event?: string;
  attribution_status?: string;
  attribution_basis?: string;
  attribution_confidence?: number;
  is_target_extension_event?: boolean;
  noise_reason?: string;
  artifact_class?: string;
  flags?: string;
  sensitive?: boolean;
  summary?: string;
}

export interface ProcessEventDto {
  timestamp?: string;
  rel_time_s?: number | null;
  pid: number;
  ppid?: number | null;
  operation?: string;
  command?: string;
  arguments_preview?: string;
  cwd?: string;
  related_extension_id?: string;
  related_activation_event?: string;
  attribution_status?: string;
  attribution_basis?: string;
  attribution_confidence?: number;
  is_target_extension_event?: boolean;
  summary?: string;
}

export interface OutputSignalEventDto {
  timestamp?: string;
  rel_time_s?: number | null;
  channel?: string;
  text?: string;
  extension_id?: string;
  activation_event?: string;
  is_target_extension_event?: boolean;
  attribution_status?: string;
  attribution_basis?: string;
  summary?: string;
}

export interface RuleExecutionRecordDto {
  rule_id: string;
  rule_version: string;
  lifecycle: RuleLifecycleDto;
  status: RuleExecutionStatusDto;
  finding_ids?: string[];
  error_detail?: string | null;
}

export type RuleExecutionStatusDto = "fired" | "silent" | "error";

export type RuleLifecycleDto = "draft" | "fixture_validated" | "smoke_validated" | "production" | "deprecated";

export interface ScenarioTraceDto {
  name: string;
  started_at: number;
  ended_at?: number;
  status?: string;
  failure_reason_code?: string;
  error_detail?: string;
}

export interface SkippedScenarioRecordDto {
  name: string;
  reason_code: string;
  detail?: string;
}

export type SeverityDto = "critical" | "high" | "medium" | "low" | "info";

export interface StimulusPassDto {
  pass_id: string;
  label: string;
  order: number;
  started_at: number;
  ended_at?: number;
  status?: string;
  trigger_method?: string;
}

export interface PrerequisiteResultDto {
  prerequisite_id: string;
  key: string;
  label: string;
  status?: string;
  materializer?: string;
  pass_name?: string;
  attempt_ids?: string[];
  detail?: string;
  reason_code?: string;
  resolved_targets?: Record<string, unknown>;
}

export interface EventAttemptDto {
  attempt_id: string;
  declared_event: string;
  activation_event: string;
  event_family: string;
  event_value?: string;
  track?: string;
  selected_by?: string;
  selection_reasons?: string[];
  pass_name?: string;
  backfill_pass_name?: string;
  prerequisite_keys?: string[];
  verification_contract?: string[];
  trigger_method?: string;
  fallback_trigger_method?: string;
  executor_action?: string;
  backfill_executor_action?: string;
  legacy_scenarios?: string[];
  capability_tags?: string[];
  status?: string;
  trigger_method_used?: string;
  attempted_passes?: string[];
  evidence?: string[];
  verification_status?: string;
  failure_reason_code?: string;
  blocked_reason_code?: string;
  result_details?: string;
  official?: boolean;
  heuristic?: boolean;
  ui_path?: string;
  harness_fallback?: string;
}

export interface LogStreamEntryDto {
  timestamp?: string;
  rel_time_s?: number | null;
  stream?: string;
  kind?: string;
  message?: string;
  extension_id?: string;
  activation_event?: string;
  scenario_name?: string;
  status?: string;
  is_target_extension?: boolean;
}

export interface RiskSignalDto {
  signal_id: string;
  category: string;
  severity: string;
  confidence: number;
  confidence_tier?: string;
  evidence_event_ids?: string[];
  summary?: string;
  details?: Record<string, unknown>;
}

export type VerdictDto = "malicious" | "suspicious" | "clean_with_notes" | "clean" | "inconclusive";

export interface ActivationReportMetadataDto {
  filename: string;
}

export interface ActivationReportDto {
  schema_version?: string;
  report_version: number;
  target_extension_expected: string;
  automation_health: AutomationHealthDto;
  signal_summary: Record<string, unknown>;
  summary: Record<string, unknown>;
  scenario_traces: ScenarioTraceDto[];
  skipped_scenarios?: SkippedScenarioRecordDto[];
  evidence_events: EvidenceEventDto[];
  network_events: NetworkEventDto[];
  file_events: FileEventDto[];
  process_events?: ProcessEventDto[];
  log_streams: LogStreamsDto;
  target_extension_observed?: boolean;
  trigger_plan_requested?: boolean;
  trigger_plan_loaded?: boolean;
  trigger_plan_applied?: boolean;
  trigger_plan_path?: string;
  trigger_execution_mode?: string;
  requested_scenarios?: string[];
  failed_scenarios?: string[];
  extra_trigger_failures?: string[];
  verification_gap?: number;
  heuristic_verification_gap?: number;
  run_quality?: string;
  run_quality_reasons?: string[];
  log_health?: LogHealthDto;
  attribution_summary?: AttributionSummaryDto;
  risk_signals?: RiskSignalDto[];
  risk_summary?: RiskSummaryDto;
  attempted_capabilities?: string[];
  verified_capabilities?: string[];
  official_attempted_capabilities?: string[];
  official_verified_capabilities?: string[];
  heuristic_attempted_capabilities?: string[];
  heuristic_verified_capabilities?: string[];
  network_capture_error?: string;
  file_capture_error?: string;
  file_capture_diagnostics?: Record<string, unknown>;
  activated?: ActivationEntryDto[];
  running_extensions?: RunningExtensionDto[];
  stimulus_passes?: StimulusPassDto[];
  prerequisite_results?: PrerequisiteResultDto[];
  event_attempts?: EventAttemptDto[];
  evidence_links?: EvidenceLinkDto[];
  network_summary?: Record<string, unknown>;
  file_summary?: Record<string, unknown>;
  coverage_summary?: CoverageSummaryDto;
  coverage_matrix?: CoverageCapabilityDto[];
  coverage_tracks?: CoverageTracksDto;
  official_event_coverage?: EventCoverageDto;
  heuristic_workflow_coverage?: EventCoverageDto;
  extension_host_output_lines?: number;
  extension_host_output?: string;
  log_file?: string;
  output_signal_events?: OutputSignalEventDto[];
  _metadata?: ActivationReportMetadataDto | null;
}

export interface MarketplaceExtensionDto {
  publisher: string;
  name: string;
  version: string;
  displayName: string;
  description: string;
  installs: number;
  rating: number;
}

export interface MarketplaceDownloadResponseDto {
  status: string;
  publisher: string;
  name: string;
  version: string;
  extension_dir: string;
  db_id?: number | null;
  message: string;
}

export interface AnalyzeJobStepDto {
  name: string;
  status: string;
  message: string;
  error_code?: string | null;
  progress?: AnalyzeJobStepProgressDto | null;
}

export interface AnalyzeJobStepProgressDto {
  completed: number;
  total: number;
}

export interface AnalyzeJobStatusDto {
  job_id: string;
  status: string;
  publisher: string;
  name: string;
  version: string;
  scenario?: string | null;
  current_step?: string | null;
  message: string;
  steps?: AnalyzeJobStepDto[];
  report_path?: string | null;
  install_output?: string | null;
  automation_output?: string | null;
  error_detail?: string | null;
  error_code?: string | null;
  created_at: number;
  started_at?: number | null;
  finished_at?: number | null;
  updated_at: number;
  detection_report?: DetectionReportDto | null;
  report_error?: string | null;
}
