"""Event-family strategies and event→scenario reverse-lookup maps.

W10-3 split from former monolithic ``registry.py``. Pure data; no behavior.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class EventStrategy:
    """Targeted strategy for an activation-event family."""

    family: str
    capability_tags: tuple[str, ...]
    executor_group: str
    prerequisites: tuple[str, ...]
    verification_contract: tuple[str, ...]
    legacy_scenarios: tuple[str, ...] = ()
    ui_path: str = ""
    harness_fallback: str | None = None
    official: bool = True
    heuristic: bool = False


_BUILTIN_VIEW_IDS = frozenset({"explorer", "extensions", "output", "scm", "search"})


OFFICIAL_EVENT_REGISTRY: dict[str, EventStrategy] = {
    "onAuthenticationRequest": EventStrategy(
        family="onAuthenticationRequest",
        capability_tags=("authentication", "window_ui"),
        executor_group="authentication_request",
        prerequisites=("auth_request_target",),
        verification_contract=("activation_log_exact", "target_runtime_delta"),
        legacy_scenarios=("authentication_probe",),
        ui_path="Accounts: Sign In or target auth consumer flow",
        harness_fallback="run_current_stimulus",
    ),
    "onChatParticipant": EventStrategy(
        family="onChatParticipant",
        capability_tags=("chat", "window_ui"),
        executor_group="chat_participant",
        prerequisites=("chat_participant_target",),
        verification_contract=("activation_log_exact", "automation_trace"),
        ui_path="Open chat and invoke participant by id",
        harness_fallback="run_current_stimulus",
    ),
    "onCommand": EventStrategy(
        family="onCommand",
        capability_tags=("commands", "window_ui"),
        executor_group="command",
        prerequisites=("command_target",),
        verification_contract=("activation_log_prefix", "target_runtime_delta"),
        legacy_scenarios=("coding_session", "refactor_workflow"),
        ui_path="Command Palette invocation",
        harness_fallback="run_current_stimulus",
    ),
    "onCustomEditor": EventStrategy(
        family="onCustomEditor",
        capability_tags=("custom_editors", "workspace_fs", "window_ui"),
        executor_group="custom_editor",
        prerequisites=("custom_editor_bait_files",),
        verification_contract=("activation_log_prefix", "target_runtime_delta"),
        ui_path="Open a bait file matched by contributes.customEditors",
        harness_fallback="run_current_stimulus",
    ),
    "onDebug": EventStrategy(
        family="onDebug",
        capability_tags=("debug", "window_ui"),
        executor_group="debug",
        prerequisites=("debug_launch_config",),
        verification_contract=("activation_log_prefix", "target_runtime_delta"),
        legacy_scenarios=("debug_session",),
        ui_path="Run and Debug sidebar workflow",
        harness_fallback="run_current_stimulus",
    ),
    "onDebugAdapterProtocolTracker": EventStrategy(
        family="onDebugAdapterProtocolTracker",
        capability_tags=("debug",),
        executor_group="debug",
        prerequisites=("debug_launch_config",),
        verification_contract=("activation_log_prefix", "target_runtime_delta"),
        legacy_scenarios=("debug_session",),
        ui_path="Start a debug session that needs protocol tracking",
        harness_fallback="run_current_stimulus",
    ),
    "onDebugDynamicConfigurations": EventStrategy(
        family="onDebugDynamicConfigurations",
        capability_tags=("debug",),
        executor_group="debug_dynamic",
        prerequisites=("debug_launch_config",),
        verification_contract=("activation_log_prefix", "automation_trace"),
        legacy_scenarios=("debug_session",),
        ui_path="Select and Start Debugging flow",
        harness_fallback="run_current_stimulus",
    ),
    "onDebugInitialConfigurations": EventStrategy(
        family="onDebugInitialConfigurations",
        capability_tags=("debug",),
        executor_group="debug_initial",
        prerequisites=("debug_launch_config",),
        verification_contract=("activation_log_prefix", "automation_trace"),
        legacy_scenarios=("debug_session",),
        ui_path="Create launch.json through Run and Debug",
        harness_fallback="run_current_stimulus",
    ),
    "onDebugResolve": EventStrategy(
        family="onDebugResolve",
        capability_tags=("debug",),
        executor_group="debug",
        prerequisites=("debug_launch_config",),
        verification_contract=("activation_log_prefix", "target_runtime_delta"),
        legacy_scenarios=("debug_session",),
        ui_path="Start a debug session with a matching debug type",
        harness_fallback="run_current_stimulus",
    ),
    "onEditSession": EventStrategy(
        family="onEditSession",
        capability_tags=("workspace_fs",),
        executor_group="edit_session",
        prerequisites=("edit_session_fixture",),
        verification_contract=("activation_log_prefix", "automation_trace"),
        ui_path="Visible edit-session commands when available",
        harness_fallback="run_current_stimulus",
    ),
    "onFileSystem": EventStrategy(
        family="onFileSystem",
        capability_tags=("workspace_fs",),
        executor_group="filesystem",
        prerequisites=("filesystem_scheme_target",),
        verification_contract=("activation_log_prefix", "target_runtime_delta"),
        ui_path="Read a document for the requested scheme",
        harness_fallback="run_current_stimulus",
    ),
    "onIssueReporterOpened": EventStrategy(
        family="onIssueReporterOpened",
        capability_tags=("window_ui",),
        executor_group="issue_reporter",
        prerequisites=(),
        verification_contract=("activation_log_exact", "automation_trace"),
        ui_path="Help: Report Issue",
        harness_fallback="run_current_stimulus",
    ),
    "onLanguage": EventStrategy(
        family="onLanguage",
        capability_tags=("languages_editor", "workspace_fs"),
        executor_group="language",
        prerequisites=("language_fixture",),
        verification_contract=("activation_log_prefix", "target_runtime_delta"),
        legacy_scenarios=("coding_session", "project_exploration"),
        ui_path="Open a file that resolves to the requested language id",
    ),
    "onLanguageModelTool": EventStrategy(
        family="onLanguageModelTool",
        capability_tags=("chat",),
        executor_group="language_model_tool",
        prerequisites=("language_model_tool_target",),
        verification_contract=("activation_log_prefix", "automation_trace"),
        ui_path="Invoke the tool from the chat/tooling surface",
        harness_fallback="run_current_stimulus",
    ),
    "onNotebook": EventStrategy(
        family="onNotebook",
        capability_tags=("notebooks", "workspace_fs"),
        executor_group="notebook",
        prerequisites=("notebook_fixture",),
        verification_contract=("activation_log_prefix", "target_runtime_delta"),
        legacy_scenarios=("notebook_session",),
        ui_path="Open a notebook document with the requested type",
        harness_fallback="run_current_stimulus",
    ),
    "onOpenExternalUri": EventStrategy(
        family="onOpenExternalUri",
        capability_tags=("uri_walkthrough", "window_ui"),
        executor_group="open_external_uri",
        prerequisites=("loopback_uri_target",),
        verification_contract=("activation_log_exact", "automation_trace"),
        ui_path="Open a loopback http/https URI",
        harness_fallback="run_current_stimulus",
    ),
    "onRenderer": EventStrategy(
        family="onRenderer",
        capability_tags=("notebooks", "webview"),
        executor_group="renderer",
        prerequisites=("renderer_fixture", "notebook_fixture"),
        verification_contract=("activation_log_prefix", "automation_trace"),
        legacy_scenarios=("notebook_session",),
        ui_path="Render notebook output that matches the renderer id",
        harness_fallback="run_current_stimulus",
    ),
    "onSearch": EventStrategy(
        family="onSearch",
        capability_tags=("search_views", "window_ui"),
        executor_group="search",
        prerequisites=("searchable_workspace",),
        verification_contract=("activation_log_prefix", "target_runtime_delta"),
        legacy_scenarios=("search_workflow",),
        ui_path="Find in Files over the requested scheme",
    ),
    "onStartupFinished": EventStrategy(
        family="onStartupFinished",
        capability_tags=("window_ui",),
        executor_group="startup_finished",
        prerequisites=("workspace_ready",),
        verification_contract=("activation_log_exact",),
        legacy_scenarios=("project_exploration",),
        ui_path="Observe startup completion after workbench warmup",
    ),
    "onTaskType": EventStrategy(
        family="onTaskType",
        capability_tags=("terminal_tasks",),
        executor_group="task_type",
        prerequisites=("task_definition_target",),
        verification_contract=("activation_log_prefix", "target_runtime_delta"),
        legacy_scenarios=("terminal_usage",),
        ui_path="Tasks: Run Task",
        harness_fallback="run_current_stimulus",
    ),
    "onTerminal": EventStrategy(
        family="onTerminal",
        capability_tags=("terminal_tasks",),
        executor_group="terminal",
        prerequisites=("terminal_shell_target",),
        verification_contract=("activation_log_prefix", "target_runtime_delta"),
        legacy_scenarios=("terminal_usage",),
        ui_path="Launch an integrated terminal for the requested shell type",
        harness_fallback="run_current_stimulus",
    ),
    "onTerminalProfile": EventStrategy(
        family="onTerminalProfile",
        capability_tags=("terminal_tasks",),
        executor_group="terminal_profile",
        prerequisites=("terminal_profile_target",),
        verification_contract=("activation_log_prefix", "target_runtime_delta"),
        legacy_scenarios=("terminal_usage",),
        ui_path="Launch the requested terminal profile",
        harness_fallback="run_current_stimulus",
    ),
    "onTerminalShellIntegration": EventStrategy(
        family="onTerminalShellIntegration",
        capability_tags=("terminal_tasks",),
        executor_group="terminal_shell_integration",
        prerequisites=("terminal_shell_target",),
        verification_contract=("activation_log_prefix", "automation_trace"),
        legacy_scenarios=("terminal_usage",),
        ui_path="Open a terminal and wait for shell integration",
        harness_fallback="run_current_stimulus",
    ),
    "onUri": EventStrategy(
        family="onUri",
        capability_tags=("uri_walkthrough", "window_ui"),
        executor_group="uri",
        prerequisites=("uri_target",),
        verification_contract=("activation_log_exact", "target_runtime_delta"),
        ui_path="Open vscode://<publisher.name>/...",
        harness_fallback="run_current_stimulus",
    ),
    "onView": EventStrategy(
        family="onView",
        capability_tags=("window_ui",),
        executor_group="view",
        prerequisites=("view_target",),
        verification_contract=("activation_log_prefix", "automation_trace"),
        legacy_scenarios=("project_exploration",),
        ui_path="Expand the contributed view in the sidebar",
        harness_fallback="run_current_stimulus",
    ),
    "onWalkthrough": EventStrategy(
        family="onWalkthrough",
        capability_tags=("uri_walkthrough", "window_ui"),
        executor_group="walkthrough",
        prerequisites=("walkthrough_target",),
        verification_contract=("activation_log_prefix", "automation_trace"),
        ui_path="Getting Started walkthrough open flow",
        harness_fallback="run_current_stimulus",
    ),
    "onWebviewPanel": EventStrategy(
        family="onWebviewPanel",
        capability_tags=("webview", "window_ui"),
        executor_group="webview_panel",
        prerequisites=("webview_target",),
        verification_contract=("activation_log_prefix", "automation_trace"),
        legacy_scenarios=("webview_probe",),
        ui_path="Restore a webview panel with the matching viewType",
        harness_fallback="run_current_stimulus",
    ),
    "workspaceContains": EventStrategy(
        family="workspaceContains",
        capability_tags=("workspace_fs", "languages_editor"),
        executor_group="workspace_contains",
        prerequisites=("workspace_contains_fixture",),
        verification_contract=("activation_log_prefix", "target_runtime_delta"),
        legacy_scenarios=("project_exploration",),
        ui_path="Open a workspace that contains the requested glob",
    ),
    "*": EventStrategy(
        family="*",
        capability_tags=("window_ui",),
        executor_group="startup",
        prerequisites=("workspace_ready",),
        verification_contract=("activation_log_exact",),
        legacy_scenarios=(
            "coding_session",
            "project_exploration",
            "diagnostics_check",
            "search_workflow",
            "debug_session",
        ),
        ui_path="Observe startup activation once the window is ready",
    ),
}


EVENT_TYPE_TO_SCENARIOS: dict[str, list[str]] = {
    "onLanguage": ["coding_session", "project_exploration"],
    "onCommand": ["coding_session", "refactor_workflow"],
    "onDebug": ["debug_session"],
    "onDebugResolve": ["debug_session"],
    "onDebugAdapterProtocolTracker": ["debug_session"],
    "onDebugDynamicConfigurations": ["debug_session"],
    "onDebugInitialConfigurations": ["debug_session"],
    "workspaceContains": ["project_exploration"],
    "onNotebook": ["notebook_session"],
    "onRenderer": ["notebook_session"],
    "onTaskType": ["terminal_usage"],
    "onTerminal": ["terminal_usage"],
    "onTerminalProfile": ["terminal_usage"],
    "onTerminalShellIntegration": ["terminal_usage"],
    "onAuthenticationRequest": ["authentication_probe"],
    "onWebviewPanel": ["webview_probe"],
    "onSearch": ["search_workflow"],
    "onWalkthrough": [],
    "onUri": [],
    "onOpenExternalUri": [],
    "onCustomEditor": [],
    "onFileSystem": [],
    "onEditSession": [],
    "onIssueReporterOpened": [],
    "onChatParticipant": [],
    "onLanguageModelTool": [],
    "onView": [],
    "onStartupFinished": [],
    "*": [],
}

HEURISTIC_EVENT_TYPE_TO_SCENARIOS: dict[str, list[str]] = {
    "onView:scm": ["git_workflow"],
    "onView:extensions": ["extension_browsing"],
    "onView:explorer": ["project_exploration"],
    "onView:search": ["search_workflow"],
    "onView:output": ["diagnostics_check"],
    "onConfiguration": ["settings_modification"],
}
