[theme]
primaryColor = "#8b5cf6"
backgroundColor = "#050505"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#f4f4f5"
font = "sans serif"
base = "dark"

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
