"""add extension_activation_events table

Revision ID: 0352a49b506f
Revises: 7ab8313406c3
Create Date: 2025-12-21 16:11:22.560984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0352a49b506f'
down_revision: Union[str, Sequence[str], None] = '7ab8313406c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extension_activation_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extension_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['extension_id'], ['extensions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extension_activation_events_event_type'), 'extension_activation_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_extension_activation_events_extension_id'), 'extension_activation_events', ['extension_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extension_activation_events_extension_id'), table_name='extension_activation_events')
    op.drop_index(op.f('ix_extension_activation_events_event_type'), table_name='extension_activation_events')
    op.drop_table('extension_activation_events')
    # ### end Alembic commands ###
