"""contributes field added

Revision ID: 10fbd4527182
Revises: 0352a49b506f
Create Date: 2025-12-21 17:59:48.738633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10fbd4527182'
down_revision: Union[str, Sequence[str], None] = '0352a49b506f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extension_contributes',
    sa.Column('extension_id', sa.Integer(), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('debuggers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('walkthroughs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('grammars', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('colors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('icons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('snippets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('views', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('viewsContainers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('themes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('iconThemes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('productIconThemes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('jsonValidation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('problemMatchers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('problemPatterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('taskDefinitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('customEditors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submenus', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('viewsWelcome', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('breakpoints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('configurationDefaults', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('typescriptServerPlugins', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['extension_id'], ['extensions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('extension_id')
    )
    op.create_table('extension_contributes_authentication',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contributes_id', sa.Integer(), nullable=False),
    sa.Column('auth_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['contributes_id'], ['extension_contributes.extension_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extension_contributes_authentication_contributes_id'), 'extension_contributes_authentication', ['contributes_id'], unique=False)
    op.create_table('extension_contributes_commands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contributes_id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('icon', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('when', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contributes_id'], ['extension_contributes.extension_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extension_contributes_commands_contributes_id'), 'extension_contributes_commands', ['contributes_id'], unique=False)
    op.create_table('extension_contributes_keybindings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contributes_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('when', sa.Text(), nullable=True),
    sa.Column('mac', sa.String(), nullable=True),
    sa.Column('linux', sa.String(), nullable=True),
    sa.Column('win', sa.String(), nullable=True),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['contributes_id'], ['extension_contributes.extension_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extension_contributes_keybindings_contributes_id'), 'extension_contributes_keybindings', ['contributes_id'], unique=False)
    op.create_table('extension_contributes_menus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contributes_id', sa.Integer(), nullable=False),
    sa.Column('menu_location', sa.String(), nullable=False),
    sa.Column('command', sa.String(), nullable=True),
    sa.Column('submenu', sa.String(), nullable=True),
    sa.Column('when', sa.Text(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('alt', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contributes_id'], ['extension_contributes.extension_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extension_contributes_menus_contributes_id'), 'extension_contributes_menus', ['contributes_id'], unique=False)
    op.create_index(op.f('ix_extension_contributes_menus_menu_location'), 'extension_contributes_menus', ['menu_location'], unique=False)
    op.create_table('extension_contributes_terminal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contributes_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contributes_id'], ['extension_contributes.extension_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extension_contributes_terminal_contributes_id'), 'extension_contributes_terminal', ['contributes_id'], unique=False)
    op.drop_index(op.f('ix_extension_commands_extension_id'), table_name='extension_commands')
    op.drop_table('extension_commands')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extension_commands',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('extension_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('command_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('icon', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('when', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['extension_id'], ['extensions.id'], name=op.f('extension_commands_extension_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('extension_commands_pkey'))
    )
    op.create_index(op.f('ix_extension_commands_extension_id'), 'extension_commands', ['extension_id'], unique=False)
    op.drop_index(op.f('ix_extension_contributes_terminal_contributes_id'), table_name='extension_contributes_terminal')
    op.drop_table('extension_contributes_terminal')
    op.drop_index(op.f('ix_extension_contributes_menus_menu_location'), table_name='extension_contributes_menus')
    op.drop_index(op.f('ix_extension_contributes_menus_contributes_id'), table_name='extension_contributes_menus')
    op.drop_table('extension_contributes_menus')
    op.drop_index(op.f('ix_extension_contributes_keybindings_contributes_id'), table_name='extension_contributes_keybindings')
    op.drop_table('extension_contributes_keybindings')
    op.drop_index(op.f('ix_extension_contributes_commands_contributes_id'), table_name='extension_contributes_commands')
    op.drop_table('extension_contributes_commands')
    op.drop_index(op.f('ix_extension_contributes_authentication_contributes_id'), table_name='extension_contributes_authentication')
    op.drop_table('extension_contributes_authentication')
    op.drop_table('extension_contributes')
    # ### end Alembic commands ###
