"""extension_capabilities table added

Revision ID: 81d0177e21f4
Revises: 89f62ee11a82
Create Date: 2025-12-18 17:25:24.573032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81d0177e21f4'
down_revision: Union[str, Sequence[str], None] = '89f62ee11a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extensions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=False),
    sa.Column('engines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('displayName', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('galleryBanner', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preview', sa.Boolean(), nullable=True),
    sa.Column('badges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=True),
    sa.Column('qna', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sponsor', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('pricing', sa.String(), nullable=True),
    sa.Column('main', sa.String(), nullable=True),
    sa.Column('web', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publisher', 'name', 'version', name='uix_publisher_name_version')
    )
    op.create_index(op.f('ix_extensions_name'), 'extensions', ['name'], unique=False)
    op.create_index(op.f('ix_extensions_publisher'), 'extensions', ['publisher'], unique=False)
    op.create_index(op.f('ix_extensions_version'), 'extensions', ['version'], unique=False)
    op.create_table('extension_capabilities',
    sa.Column('extension_id', sa.Integer(), nullable=False),
    sa.Column('untrusted_supported', sa.Enum('supported', 'not_supported', 'limited', name='capability_support_state'), nullable=True),
    sa.Column('untrusted_description', sa.Text(), nullable=True),
    sa.Column('untrusted_restricted_configurations', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('virtual_supported', sa.Enum('supported', 'not_supported', 'limited', name='capability_support_state'), nullable=True),
    sa.Column('virtual_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['extension_id'], ['extensions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('extension_id')
    )
    op.create_table('extension_commands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extension_id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('icon', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('when', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['extension_id'], ['extensions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extension_commands_extension_id'), 'extension_commands', ['extension_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extension_commands_extension_id'), table_name='extension_commands')
    op.drop_table('extension_commands')
    op.drop_table('extension_capabilities')
    op.drop_index(op.f('ix_extensions_version'), table_name='extensions')
    op.drop_index(op.f('ix_extensions_publisher'), table_name='extensions')
    op.drop_index(op.f('ix_extensions_name'), table_name='extensions')
    op.drop_table('extensions')
    # ### end Alembic commands ###
