"""uix_publisher_name contraint renamed to uix_publisher_name_version

Revision ID: 89f62ee11a82
Revises: d96023531af8
Create Date: 2025-12-16 17:37:12.627263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89f62ee11a82'
down_revision: Union[str, Sequence[str], None] = 'd96023531af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extension_commands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extension_id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('icon', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['extension_id'], ['extensions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extension_commands_extension_id'), 'extension_commands', ['extension_id'], unique=False)
    op.drop_constraint(op.f('uix_publisher_name'), 'extensions', type_='unique')
    op.create_unique_constraint('uix_publisher_name_version', 'extensions', ['publisher', 'name', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_publisher_name_version', 'extensions', type_='unique')
    op.create_unique_constraint(op.f('uix_publisher_name'), 'extensions', ['publisher', 'name', 'version'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_extension_commands_extension_id'), table_name='extension_commands')
    op.drop_table('extension_commands')
    # ### end Alembic commands ###
