"""devdependencies and dependencies rows added to extension table

Revision ID: 972a85ca728a
Revises: 9ba87e1b42e9
Create Date: 2025-12-21 14:06:24.082858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '972a85ca728a'
down_revision: Union[str, Sequence[str], None] = '9ba87e1b42e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extensions', sa.Column('dependencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('extensions', sa.Column('devDependencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extensions', 'devDependencies')
    op.drop_column('extensions', 'dependencies')
    # ### end Alembic commands ###
