"""add_extension_scripts_table

Revision ID: 9ba87e1b42e9
Revises: 81d0177e21f4
Create Date: 2025-12-18 20:11:44.607315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ba87e1b42e9'
down_revision: Union[str, Sequence[str], None] = '81d0177e21f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extension_scripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extension_id', sa.Integer(), nullable=False),
    sa.Column('script_name', sa.String(), nullable=False),
    sa.Column('script_command', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['extension_id'], ['extensions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extension_scripts_extension_id'), 'extension_scripts', ['extension_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extension_scripts_extension_id'), table_name='extension_scripts')
    op.drop_table('extension_scripts')
    # ### end Alembic commands ###
