"""indexes added to fix latency problem

Revision ID: b00fdc9411ca
Revises: 10fbd4527182
Create Date: 2025-12-21 19:51:08.770795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b00fdc9411ca'
down_revision: Union[str, Sequence[str], None] = '10fbd4527182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_extensions_publisher_name', 'extensions', ['publisher', 'name'], unique=False)
    op.create_index('ix_extensions_publisher_name_version', 'extensions', ['publisher', 'name', 'version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_extensions_publisher_name_version', table_name='extensions')
    op.drop_index('ix_extensions_publisher_name', table_name='extensions')
    # ### end Alembic commands ###
