"""npm fields and extra fields added. web column name changed to browser

Revision ID: d50003b4c96e
Revises: b00fdc9411ca
Create Date: 2025-12-22 12:55:48.779633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd50003b4c96e'
down_revision: Union[str, Sequence[str], None] = 'b00fdc9411ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extensions', sa.Column('browser', sa.String(), nullable=True))
    op.add_column('extensions', sa.Column('npm_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('extensions', sa.Column('extra_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('extensions', 'web')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extensions', sa.Column('web', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('extensions', 'extra_fields')
    op.drop_column('extensions', 'npm_fields')
    op.drop_column('extensions', 'browser')
    # ### end Alembic commands ###
