"""version column added to extension table

Revision ID: d96023531af8
Revises: d3762e149486
Create Date: 2025-12-16 11:54:44.646724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd96023531af8'
down_revision: Union[str, Sequence[str], None] = 'd3762e149486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add column as nullable first (to handle existing rows)
    op.add_column('extensions', sa.Column('version', sa.String(), nullable=True))
    
    # Step 2: Set default value for existing rows
    op.execute("UPDATE extensions SET version = '0.0.0' WHERE version IS NULL")
    
    # Step 3: Make the column NOT NULL now that all rows have values
    op.alter_column('extensions', 'version', nullable=False)
    
    # Step 4: Update constraints and indexes
    op.drop_constraint(op.f('uix_publisher_name'), 'extensions', type_='unique')
    op.create_unique_constraint('uix_publisher_name', 'extensions', ['publisher', 'name', 'version'])
    op.create_index(op.f('ix_extensions_version'), 'extensions', ['version'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extensions_version'), table_name='extensions')
    op.drop_constraint('uix_publisher_name', 'extensions', type_='unique')
    op.create_unique_constraint(op.f('uix_publisher_name'), 'extensions', ['publisher', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_column('extensions', 'version')
    # ### end Alembic commands ###
