"""Backend-owned analysis contracts."""

from packages.analysis_contracts.contracts import (
    ActivationEntry,
    ActivationReport,
    ActivationReportFileSummary,
    EventAttemptRecord,
    EvidenceEvent,
    EvidenceLink,
    FileEvent,
    LogStreamEntry,
    NetworkEvent,
    PrerequisiteResult,
    RiskSignal,
    RunningExtension,
    ScenarioTrace,
    StimulusPassTrace,
    TriggerPayload,
    TriggerScenarioDetail,
    TriggerStimulusPass,
)
from packages.analysis_contracts.detection import (
    AdversaryClass,
    AutomationHealthStatus,
    Confidence,
    DetectionFinding,
    DetectionReport,
    EvidenceRef,
    ExtensionIdentity,
    RuleExecutionRecord,
    RuleExecutionStatus,
    RuleLifecycle,
    Severity,
    Verdict,
    compute_verdict,
)
from packages.analysis_contracts.report_invariants import (
    activation_report_invariant_issues,
    scenario_trace_names,
)

__all__ = [
    "ActivationEntry",
    "ActivationReport",
    "ActivationReportFileSummary",
    "AdversaryClass",
    "AutomationHealthStatus",
    "Confidence",
    "DetectionFinding",
    "DetectionReport",
    "EventAttemptRecord",
    "EvidenceEvent",
    "EvidenceLink",
    "EvidenceRef",
    "ExtensionIdentity",
    "FileEvent",
    "LogStreamEntry",
    "NetworkEvent",
    "PrerequisiteResult",
    "RiskSignal",
    "RuleExecutionRecord",
    "RuleExecutionStatus",
    "RuleLifecycle",
    "RunningExtension",
    "ScenarioTrace",
    "Severity",
    "StimulusPassTrace",
    "TriggerPayload",
    "TriggerScenarioDetail",
    "TriggerStimulusPass",
    "Verdict",
    "activation_report_invariant_issues",
    "compute_verdict",
    "scenario_trace_names",
]
