"""Backend-owned analysis contracts."""

# Import everything contract-related from contracts.py — it is the single
# entry that resolves the contracts <-> automation/coverage circular
# dependency in the right order. Importing AutomationHealth/CoverageSummary
# directly from their dedicated modules here would have ruff re-order the
# import block alphabetically (automation < contracts) and re-introduce the
# circular import, so we lean on the contracts.py re-export instead.
from packages.analysis_contracts.contracts import (
    ACTIVATION_REPORT_SCHEMA_VERSION,
    EVENT_ATTEMPT_LIFECYCLE_STATES,
    ActivationEntry,
    ActivationReport,
    ActivationReportFileSummary,
    AutomationHealth,
    AutomationHealthStatusLiteral,
    CoverageSummary,
    EventAttemptRecord,
    EvidenceEvent,
    EvidenceLink,
    FileEvent,
    LogStreamEntry,
    NetworkEvent,
    PrerequisiteResult,
    ProcessEvent,
    RiskSignal,
    RunnerStatusLiteral,
    RunningExtension,
    ScenarioTrace,
    SkippedScenarioRecord,
    StimulusPassTrace,
    TriggerPayload,
    TriggerScenarioDetail,
    TriggerStimulusPass,
)
from packages.analysis_contracts.detection import (
    AdversaryClass,
    AutomationHealthStatus,
    Confidence,
    DetectionFinding,
    DetectionReport,
    EvidenceRef,
    ExtensionIdentity,
    RuleExecutionRecord,
    RuleExecutionStatus,
    RuleLifecycle,
    Severity,
    Verdict,
    compute_verdict,
    quantize_confidence,
)
from packages.analysis_contracts.evidence import (
    SECRET_CLASSES,
    ActivationRawContext,
    ContentSample,
    FileRawContext,
    NetworkRawContext,
    OutputChannelRawContext,
    ProcessRawContext,
    RawContext,
    ScenarioRawContext,
    UiBlockerRawContext,
    redact_multiline_secrets,
    redact_secrets,
)
from packages.analysis_contracts.executor_actions import (
    EXECUTOR_ACTION_NAMESPACES,
    EXTRA_EXECUTOR_ACTIONS,
    validate_executor_action,
)
from packages.analysis_contracts.report_invariants import (
    activation_report_invariant_issues,
    detection_report_invariant_issues,
    scenario_trace_names,
)

__all__ = [
    "ACTIVATION_REPORT_SCHEMA_VERSION",
    "EVENT_ATTEMPT_LIFECYCLE_STATES",
    "EXECUTOR_ACTION_NAMESPACES",
    "EXTRA_EXECUTOR_ACTIONS",
    "SECRET_CLASSES",
    "ActivationEntry",
    "ActivationRawContext",
    "ActivationReport",
    "ActivationReportFileSummary",
    "AdversaryClass",
    "AutomationHealth",
    "AutomationHealthStatus",
    "AutomationHealthStatusLiteral",
    "Confidence",
    "ContentSample",
    "CoverageSummary",
    "DetectionFinding",
    "DetectionReport",
    "EventAttemptRecord",
    "EvidenceEvent",
    "EvidenceLink",
    "EvidenceRef",
    "ExtensionIdentity",
    "FileEvent",
    "FileRawContext",
    "LogStreamEntry",
    "NetworkEvent",
    "NetworkRawContext",
    "OutputChannelRawContext",
    "PrerequisiteResult",
    "ProcessEvent",
    "ProcessRawContext",
    "RawContext",
    "RiskSignal",
    "RuleExecutionRecord",
    "RuleExecutionStatus",
    "RuleLifecycle",
    "RunnerStatusLiteral",
    "RunningExtension",
    "ScenarioRawContext",
    "ScenarioTrace",
    "Severity",
    "SkippedScenarioRecord",
    "StimulusPassTrace",
    "TriggerPayload",
    "TriggerScenarioDetail",
    "TriggerStimulusPass",
    "UiBlockerRawContext",
    "Verdict",
    "activation_report_invariant_issues",
    "compute_verdict",
    "detection_report_invariant_issues",
    "quantize_confidence",
    "redact_multiline_secrets",
    "redact_secrets",
    "scenario_trace_names",
    "validate_executor_action",
]
