from __future__ import annotations

import argparse
import importlib
import os
import sys
from collections.abc import Mapping
from enum import Enum
from pathlib import Path
from typing import Any

from pydantic import BaseModel, TypeAdapter

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

OUTPUT_PATH = REPO_ROOT / "ui" / "src" / "lib" / "types" / "contracts.ts"
GENERATED_HEADER = (
    "// Generated by scripts/generate_ui_contracts.py.\n"
    "// Do not edit this file manually.\n\n"
)

TARGET_SCHEMAS: list[str] = [
    "AnalysisBundle",
    "ReportBundle",
    "ActivationReportFileSummary",
    "ActivationEntry",
    "AdversaryClass",
    "Confidence",
    "DetectionFinding",
    "DetectionReport",
    "EvidenceRef",
    "ExtensionIdentity",
    "RunningExtension",
    "EvidenceEvent",
    "EvidenceLink",
    "NetworkEvent",
    "FileEvent",
    "ProcessEvent",
    "OutputSignalEvent",
    "NetworkRawContext",
    "FileRawContext",
    "ProcessRawContext",
    "ScenarioRawContext",
    "ActivationRawContext",
    "UiBlockerRawContext",
    "OutputChannelRawContext",
    "RuleExecutionRecord",
    "RuleExecutionStatus",
    "RuleLifecycle",
    "ScenarioTrace",
    "SkippedScenarioRecord",
    "Severity",
    "StimulusPassTrace",
    "PrerequisiteResult",
    "EventAttemptRecord",
    "LogStreamEntry",
    "RiskSignal",
    "Verdict",
    "ActivationReportMetadata",
    "ActivationReportResponse",
    "MarketplaceExtension",
    "OfflineExtension",
    "VsixExtractionMetrics",
    "ThresholdBoundsResponse",
    "ThresholdsResponse",
    "ThresholdsUpdateRequest",
    "VsixThresholdBreachDetail",
    "MarketplaceDownloadResponse",
    "AnalyzeJobStep",
    "AnalyzeJobStepProgress",
    "AnalyzeJobStatusResponse",
    # ES-5 (ADR 0016): static pre-check report types surfaced on
    # AnalyzeJobStatusResponse.static_report. The reused enums (Severity /
    # Confidence / RuleLifecycle / AdversaryClass) are already declared above.
    "StaticGateDecision",
    "StaticGateOutcome",
    "StaticEvidenceRef",
    "StaticDetectionFinding",
    "StaticToolExecutionRecord",
    "StaticSeverityCounts",
    "StaticDetectionReport",
    "StaticAnalysisReport",
]

NAME_OVERRIDES: dict[str, str] = {
    "AnalysisBundle": "AnalysisBundleDto",
    "ReportBundle": "ReportBundleDto",
    "ActivationReportFileSummary": "ReportListItemDto",
    "ActivationEntry": "ActivationEntryDto",
    "AdversaryClass": "AdversaryClassDto",
    "Confidence": "ConfidenceDto",
    "DetectionFinding": "DetectionFindingDto",
    "DetectionReport": "DetectionReportDto",
    "EvidenceRef": "EvidenceRefDto",
    "ExtensionIdentity": "ExtensionIdentityDto",
    "RunningExtension": "RunningExtensionDto",
    "EvidenceEvent": "EvidenceEventDto",
    "EvidenceLink": "EvidenceLinkDto",
    "NetworkEvent": "NetworkEventDto",
    "FileEvent": "FileEventDto",
    "ProcessEvent": "ProcessEventDto",
    "OutputSignalEvent": "OutputSignalEventDto",
    "NetworkRawContext": "NetworkRawContextDto",
    "FileRawContext": "FileRawContextDto",
    "ProcessRawContext": "ProcessRawContextDto",
    "ScenarioRawContext": "ScenarioRawContextDto",
    "ActivationRawContext": "ActivationRawContextDto",
    "UiBlockerRawContext": "UiBlockerRawContextDto",
    "OutputChannelRawContext": "OutputChannelRawContextDto",
    "RuleExecutionRecord": "RuleExecutionRecordDto",
    "RuleExecutionStatus": "RuleExecutionStatusDto",
    "RuleLifecycle": "RuleLifecycleDto",
    "ScenarioTrace": "ScenarioTraceDto",
    "SkippedScenarioRecord": "SkippedScenarioRecordDto",
    "Severity": "SeverityDto",
    "StimulusPassTrace": "StimulusPassDto",
    "PrerequisiteResult": "PrerequisiteResultDto",
    "EventAttemptRecord": "EventAttemptDto",
    "LogStreamEntry": "LogStreamEntryDto",
    "RiskSignal": "RiskSignalDto",
    "Verdict": "VerdictDto",
    "ActivationReportMetadata": "ActivationReportMetadataDto",
    "ActivationReportResponse": "ActivationReportDto",
    "MarketplaceExtension": "MarketplaceExtensionDto",
    "OfflineExtension": "OfflineExtensionDto",
    "ThresholdBoundsResponse": "VsixThresholdBoundsDto",
    "ThresholdsResponse": "VsixThresholdsResponseDto",
    "ThresholdsUpdateRequest": "VsixThresholdsUpdateRequestDto",
    "VsixThresholdBreachDetail": "VsixThresholdBreachDetail",
    "MarketplaceDownloadResponse": "MarketplaceDownloadResponseDto",
    "AnalyzeJobStep": "AnalyzeJobStepDto",
    "AnalyzeJobStatusResponse": "AnalyzeJobStatusDto",
    # ES-5 (ADR 0016): static pre-check report DTOs.
    "StaticGateDecision": "StaticGateDecisionDto",
    "StaticGateOutcome": "StaticGateOutcomeDto",
    "StaticEvidenceRef": "StaticEvidenceRefDto",
    "StaticDetectionFinding": "StaticDetectionFindingDto",
    "StaticToolExecutionRecord": "StaticToolExecutionRecordDto",
    "StaticSeverityCounts": "StaticSeverityCountsDto",
    "StaticDetectionReport": "StaticDetectionReportDto",
    "StaticAnalysisReport": "StaticAnalysisReportDto",
}

FIELD_TYPE_OVERRIDES: dict[tuple[str, str], str] = {
    ("ActivationReportResponse", "automation_health"): "AutomationHealthDto",
    ("ActivationReportResponse", "log_health"): "LogHealthDto",
    ("ActivationReportResponse", "attribution_summary"): "AttributionSummaryDto",
    ("ActivationReportResponse", "risk_summary"): "RiskSummaryDto",
    ("ActivationReportResponse", "summary"): "Record<string, unknown>",
    ("ActivationReportResponse", "network_summary"): "Record<string, unknown>",
    ("ActivationReportResponse", "file_summary"): "Record<string, unknown>",
    ("ActivationReportResponse", "coverage_summary"): "CoverageSummaryDto",
    ("ActivationReportResponse", "coverage_matrix"): "CoverageCapabilityDto[]",
    ("ActivationReportResponse", "coverage_tracks"): "CoverageTracksDto",
    ("ActivationReportResponse", "official_event_coverage"): "EventCoverageDto",
    ("ActivationReportResponse", "heuristic_workflow_coverage"): "EventCoverageDto",
    ("ActivationReportResponse", "log_streams"): "LogStreamsDto",
    ("VsixThresholdBreachDetail", "error"): '"vsix_threshold_breach"',
    ("VsixThresholdBreachDetail", "breach_kind"): (
        '"entry_count" | "uncompressed_size" | "compression_ratio"'
    ),
}

SUPPLEMENTAL_TYPES = """export interface AutomationHealthDto {
  status?: "healthy" | "degraded" | "inconclusive";
  reasons?: string[];
  trigger_requested?: boolean;
  trigger_loaded?: boolean;
  trigger_applied?: boolean;
  extension_host_log_present?: boolean;
  extension_host_log_found?: boolean;
  extension_host_output_present?: boolean;
  target_stream_present?: boolean;
  target_activation_count?: number;
  failed_scenarios?: string[];
  extra_trigger_failures?: string[];
  extra_trigger_failure_count?: number;
  skipped_scenarios?: string[];
}

export interface LogHealthDto {
  extension_host_log_found?: boolean;
  extension_host_output_present?: boolean;
  target_extension_log_entries?: number;
  total_activation_entries?: number;
}

export interface AttributionSummaryDto {
  target_activation_count?: number;
  strong_target_file_event_count?: number;
  strong_target_network_event_count?: number;
  correlated_only_event_count?: number;
  target_background_activation_count?: number;
  competing_extension_event_count?: number;
  ui_blocker_count?: number;
}

export interface RiskSummaryDto {
  total_signals?: number;
  critical?: number;
  high?: number;
  medium?: number;
  low?: number;
  categories?: string[];
}

export interface CoverageSummaryDto {
  covered?: number;
  partial?: number;
  missing?: number;
  attempted?: number;
  verified?: number;
  covered_capabilities?: string[];
  partial_capabilities?: string[];
  missing_capabilities?: string[];
  attempted_capabilities?: string[];
  verified_capabilities?: string[];
}

export interface CoverageCapabilityDto {
  capability: string;
  status: string;
  track?: string;
  source?: string;
  support_status?: string;
  verification_status?: string;
  selected_scenarios?: string[];
  supported_scenarios?: string[];
  notes?: string;
  is_active?: boolean;
  selected?: boolean;
  attempted?: boolean;
  verified?: boolean;
}

export interface CoverageTrackDto {
  source?: string;
  selected_scenarios?: string[];
  summary?: CoverageSummaryDto;
  matrix?: CoverageCapabilityDto[];
}

export interface CoverageTracksDto {
  official?: CoverageTrackDto;
  heuristic?: CoverageTrackDto;
}

export interface EventCoverageDto {
  track?: string;
  declared?: number;
  verified?: number;
  attempted_only?: number;
  failed?: number;
  blocked?: number;
  unresolved?: number;
  declared_events?: string[];
}

export interface LogStreamsDto {
  target_extension_host?: LogStreamEntryDto[];
  other_extension_host?: LogStreamEntryDto[];
  automation?: LogStreamEntryDto[];
  ui_blockers?: LogStreamEntryDto[];
}
"""

EXTRA_SCHEMA_PROVIDERS: dict[str, type[BaseModel] | type[Enum]] = {}


def _load_openapi_schemas() -> dict[str, Any]:
    os.environ.setdefault("EXTRACE_SKIP_JOB_RECOVERY", "1")
    main_module = importlib.import_module("main")
    openapi = main_module.app.openapi()
    schemas = openapi.get("components", {}).get("schemas", {})
    if not isinstance(schemas, dict):
        raise RuntimeError("OpenAPI components.schemas payload is missing.")
    return schemas


def _load_extra_schema_providers() -> dict[str, type[BaseModel] | type[Enum]]:
    global EXTRA_SCHEMA_PROVIDERS
    if EXTRA_SCHEMA_PROVIDERS:
        return EXTRA_SCHEMA_PROVIDERS

    detection_module = importlib.import_module("packages.analysis_contracts.detection")
    detection_provider_names = [
        "AdversaryClass",
        "Confidence",
        "DetectionFinding",
        "DetectionReport",
        "EvidenceRef",
        "ExtensionIdentity",
        "RuleExecutionRecord",
        "RuleExecutionStatus",
        "RuleLifecycle",
        "Severity",
        "Verdict",
    ]
    contract_module = importlib.import_module("appcore.contracts.schemas")
    contract_provider_names = [
        # AnalysisBundle is no longer a route response_model (the Reports bundle
        # route returns its ReportBundle subclass, which OpenAPI inlines), so it
        # must be sourced from the contract module to stay emitted.
        "AnalysisBundle",
        "VsixThresholdBreachDetail",
    ]
    EXTRA_SCHEMA_PROVIDERS = {
        name: getattr(detection_module, name) for name in detection_provider_names
    }
    EXTRA_SCHEMA_PROVIDERS.update(
        {name: getattr(contract_module, name) for name in contract_provider_names}
    )
    return EXTRA_SCHEMA_PROVIDERS


def _schema_from_provider(provider: type[BaseModel] | type[Enum]) -> dict[str, Any]:
    if isinstance(provider, type) and issubclass(provider, BaseModel):
        schema = provider.model_json_schema(ref_template="#/components/schemas/{model}")
        defs = schema.pop("$defs", {})
        flattened: dict[str, Any] = {}
        if isinstance(defs, Mapping):
            flattened.update(defs)
        title = schema.get("title")
        if isinstance(title, str):
            flattened[title] = schema
        return flattened

    schema = TypeAdapter(provider).json_schema(
        ref_template="#/components/schemas/{model}"
    )
    title = schema.get("title")
    if not isinstance(title, str):
        raise RuntimeError(f"Unnamed schema provider: {provider!r}")
    return {title: schema}


def _merge_schema_sources() -> dict[str, Any]:
    schemas = dict(_load_openapi_schemas())
    for provider in _load_extra_schema_providers().values():
        for name, schema in _schema_from_provider(provider).items():
            schemas.setdefault(name, schema)
    return schemas


def _assert_target_schemas_exist(schemas: Mapping[str, Any]) -> None:
    missing = [name for name in TARGET_SCHEMAS if name not in schemas]
    if missing:
        raise RuntimeError(
            "OpenAPI is missing required schemas for UI contract generation: "
            + ", ".join(sorted(missing))
        )


def _schema_to_ts_name(schema_name: str) -> str:
    return NAME_OVERRIDES.get(schema_name, f"{schema_name}Dto")


def _ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _quoted_literal(value: Any) -> str:
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return str(value)


def _normalize_union(types: list[str]) -> str:
    seen: list[str] = []
    for item in types:
        if item not in seen:
            seen.append(item)
    return " | ".join(seen) if seen else "unknown"


def _schema_to_ts_type(
    schema: Mapping[str, Any] | None,
    *,
    parent_schema: str,
    property_name: str | None = None,
) -> str:
    if schema is None:
        return "unknown"

    if property_name is not None:
        override = FIELD_TYPE_OVERRIDES.get((parent_schema, property_name))
        if override is not None:
            return override

    ref = schema.get("$ref")
    if isinstance(ref, str):
        return _schema_to_ts_name(_ref_name(ref))

    enum_values = schema.get("enum")
    if isinstance(enum_values, list) and enum_values:
        return _normalize_union([_quoted_literal(item) for item in enum_values])

    if "const" in schema:
        return _quoted_literal(schema["const"])

    any_of = schema.get("anyOf")
    if isinstance(any_of, list) and any_of:
        return _normalize_union(
            [
                "null"
                if item.get("type") == "null"
                else _schema_to_ts_type(
                    item,
                    parent_schema=parent_schema,
                    property_name=property_name,
                )
                for item in any_of
            ]
        )

    one_of = schema.get("oneOf")
    if isinstance(one_of, list) and one_of:
        return _normalize_union(
            [
                _schema_to_ts_type(
                    item,
                    parent_schema=parent_schema,
                    property_name=property_name,
                )
                for item in one_of
            ]
        )

    schema_type = schema.get("type")
    if schema_type == "array":
        items = schema.get("items")
        item_type = _schema_to_ts_type(
            items if isinstance(items, Mapping) else None,
            parent_schema=parent_schema,
            property_name=property_name,
        )
        if " | " in item_type:
            return f"({item_type})[]"
        return f"{item_type}[]"

    if schema_type == "object":
        properties = schema.get("properties")
        if isinstance(properties, Mapping) and properties:
            required = set(schema.get("required", []))
            members: list[str] = []
            for key, value in properties.items():
                optional = "?" if key not in required else ""
                member_type = _schema_to_ts_type(
                    value,
                    parent_schema=parent_schema,
                    property_name=key,
                )
                members.append(f"{key}{optional}: {member_type};")
            return "{ " + " ".join(members) + " }"

        additional = schema.get("additionalProperties")
        if additional is True:
            return "Record<string, unknown>"
        if isinstance(additional, Mapping):
            value_type = _schema_to_ts_type(
                additional,
                parent_schema=parent_schema,
                property_name=property_name,
            )
            return f"Record<string, {value_type}>"
        return "Record<string, unknown>"

    if schema_type == "integer" or schema_type == "number":
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "string":
        return "string"
    if schema_type == "null":
        return "null"

    return "unknown"


def _emit_interface(schema_name: str, schema: Mapping[str, Any]) -> str:
    ts_name = _schema_to_ts_name(schema_name)
    properties = schema.get("properties")
    if not isinstance(properties, Mapping):
        raise RuntimeError(f"{schema_name} is not an object schema.")

    required = set(schema.get("required", []))
    lines = [f"export interface {ts_name} {{"]
    for property_name, property_schema in properties.items():
        optional = "?" if property_name not in required else ""
        property_type = _schema_to_ts_type(
            property_schema if isinstance(property_schema, Mapping) else None,
            parent_schema=schema_name,
            property_name=property_name,
        )
        lines.append(f"  {property_name}{optional}: {property_type};")
    lines.append("}")
    return "\n".join(lines)


def _emit_type_alias(schema_name: str, schema: Mapping[str, Any]) -> str:
    ts_name = _schema_to_ts_name(schema_name)
    ts_type = _schema_to_ts_type(schema, parent_schema=schema_name)
    return f"export type {ts_name} = {ts_type};"


def _emit_declaration(schema_name: str, schema: Mapping[str, Any]) -> str:
    schema_type = schema.get("type")
    if schema_type == "object" or isinstance(schema.get("properties"), Mapping):
        return _emit_interface(schema_name, schema)
    return _emit_type_alias(schema_name, schema)


def _render_contracts(schemas: Mapping[str, Any]) -> str:
    blocks = [SUPPLEMENTAL_TYPES.rstrip()]
    for schema_name in TARGET_SCHEMAS:
        schema = schemas[schema_name]
        blocks.append(_emit_declaration(schema_name, schema))
    return GENERATED_HEADER + "\n\n".join(blocks) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate backend-owned UI contract types."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the generated UI contracts would change.",
    )
    args = parser.parse_args()

    schemas = _merge_schema_sources()
    _assert_target_schemas_exist(schemas)
    rendered = _render_contracts(schemas)

    if args.check:
        current = OUTPUT_PATH.read_text(encoding="utf-8")
        if current != rendered:
            raise SystemExit(
                "Generated UI contracts are out of date. Run "
                "python scripts/generate_ui_contracts.py to refresh them."
            )
        return

    OUTPUT_PATH.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()
