from __future__ import annotations

import argparse
import importlib
import os
import sys
from collections.abc import Mapping
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

OUTPUT_PATH = REPO_ROOT / "ui" / "src" / "lib" / "types" / "contracts.ts"
GENERATED_HEADER = (
    "// Generated by scripts/generate_ui_contracts.py.\n"
    "// Do not edit this file manually.\n\n"
)

TARGET_SCHEMAS: list[str] = [
    "ActivationReportFileSummary",
    "ActivationEntry",
    "RunningExtension",
    "EvidenceEvent",
    "EvidenceLink",
    "NetworkEvent",
    "FileEvent",
    "ScenarioTrace",
    "StimulusPassTrace",
    "PrerequisiteResult",
    "EventAttemptRecord",
    "LogStreamEntry",
    "RiskSignal",
    "ActivationReportMetadata",
    "ActivationReportResponse",
    "MarketplaceExtension",
    "MarketplaceDownloadResponse",
    "AnalyzeJobStep",
    "AnalyzeJobStatusResponse",
]

NAME_OVERRIDES: dict[str, str] = {
    "ActivationReportFileSummary": "ReportListItemDto",
    "ActivationEntry": "ActivationEntryDto",
    "RunningExtension": "RunningExtensionDto",
    "EvidenceEvent": "EvidenceEventDto",
    "EvidenceLink": "EvidenceLinkDto",
    "NetworkEvent": "NetworkEventDto",
    "FileEvent": "FileEventDto",
    "ScenarioTrace": "ScenarioTraceDto",
    "StimulusPassTrace": "StimulusPassDto",
    "PrerequisiteResult": "PrerequisiteResultDto",
    "EventAttemptRecord": "EventAttemptDto",
    "LogStreamEntry": "LogStreamEntryDto",
    "RiskSignal": "RiskSignalDto",
    "ActivationReportMetadata": "ActivationReportMetadataDto",
    "ActivationReportResponse": "ActivationReportDto",
    "MarketplaceExtension": "MarketplaceExtensionDto",
    "MarketplaceDownloadResponse": "MarketplaceDownloadResponseDto",
    "AnalyzeJobStep": "AnalyzeJobStepDto",
    "AnalyzeJobStatusResponse": "AnalyzeJobStatusDto",
}

FIELD_TYPE_OVERRIDES: dict[tuple[str, str], str] = {
    ("ActivationReportResponse", "automation_health"): "AutomationHealthDto",
    ("ActivationReportResponse", "log_health"): "LogHealthDto",
    ("ActivationReportResponse", "attribution_summary"): "AttributionSummaryDto",
    ("ActivationReportResponse", "risk_summary"): "RiskSummaryDto",
    ("ActivationReportResponse", "summary"): "Record<string, unknown>",
    ("ActivationReportResponse", "network_summary"): "Record<string, unknown>",
    ("ActivationReportResponse", "file_summary"): "Record<string, unknown>",
    ("ActivationReportResponse", "coverage_summary"): "CoverageSummaryDto",
    ("ActivationReportResponse", "coverage_matrix"): "CoverageCapabilityDto[]",
    ("ActivationReportResponse", "coverage_tracks"): "CoverageTracksDto",
    ("ActivationReportResponse", "official_event_coverage"): "EventCoverageDto",
    ("ActivationReportResponse", "heuristic_workflow_coverage"): "EventCoverageDto",
    ("ActivationReportResponse", "log_streams"): "LogStreamsDto",
}

SUPPLEMENTAL_TYPES = """export interface AutomationHealthDto {
  status?: "healthy" | "degraded" | "inconclusive";
  reasons?: string[];
  trigger_requested?: boolean;
  trigger_loaded?: boolean;
  trigger_applied?: boolean;
  extension_host_log_present?: boolean;
  extension_host_output_present?: boolean;
  target_stream_present?: boolean;
  target_activation_count?: number;
  failed_scenarios?: string[];
}

export interface LogHealthDto {
  extension_host_log_found?: boolean;
  extension_host_output_present?: boolean;
  target_extension_log_entries?: number;
  total_activation_entries?: number;
}

export interface AttributionSummaryDto {
  target_activation_count?: number;
  strong_target_file_event_count?: number;
  strong_target_network_event_count?: number;
  correlated_only_event_count?: number;
  background_activation_count?: number;
  competing_candidate_count?: number;
  ui_blocker_count?: number;
}

export interface RiskSummaryDto {
  total_signals?: number;
  critical?: number;
  high?: number;
  medium?: number;
  low?: number;
  categories?: string[];
}

export interface CoverageSummaryDto {
  covered?: number;
  partial?: number;
  missing?: number;
  attempted?: number;
  verified?: number;
  covered_capabilities?: string[];
  partial_capabilities?: string[];
  missing_capabilities?: string[];
  attempted_capabilities?: string[];
  verified_capabilities?: string[];
}

export interface CoverageCapabilityDto {
  capability: string;
  status: string;
  track?: string;
  source?: string;
  support_status?: string;
  verification_status?: string;
  selected_scenarios?: string[];
  supported_scenarios?: string[];
  notes?: string;
  is_active?: boolean;
  selected?: boolean;
  attempted?: boolean;
  verified?: boolean;
}

export interface CoverageTrackDto {
  source?: string;
  selected_scenarios?: string[];
  summary?: CoverageSummaryDto;
  matrix?: CoverageCapabilityDto[];
}

export interface CoverageTracksDto {
  official?: CoverageTrackDto;
  heuristic?: CoverageTrackDto;
}

export interface EventCoverageDto {
  track?: string;
  declared?: number;
  verified?: number;
  attempted_only?: number;
  failed?: number;
  blocked?: number;
  unresolved?: number;
  declared_events?: string[];
}

export interface LogStreamsDto {
  target_extension_host?: LogStreamEntryDto[];
  other_extension_host?: LogStreamEntryDto[];
  automation?: LogStreamEntryDto[];
  ui_blockers?: LogStreamEntryDto[];
}
"""


def _load_openapi_schemas() -> dict[str, Any]:
    os.environ.setdefault("EXTRACE_SKIP_JOB_RECOVERY", "1")
    main_module = importlib.import_module("main")
    openapi = main_module.app.openapi()
    schemas = openapi.get("components", {}).get("schemas", {})
    if not isinstance(schemas, dict):
        raise RuntimeError("OpenAPI components.schemas payload is missing.")
    return schemas


def _assert_target_schemas_exist(schemas: Mapping[str, Any]) -> None:
    missing = [name for name in TARGET_SCHEMAS if name not in schemas]
    if missing:
        raise RuntimeError(
            "OpenAPI is missing required schemas for UI contract generation: "
            + ", ".join(sorted(missing))
        )


def _schema_to_ts_name(schema_name: str) -> str:
    return NAME_OVERRIDES.get(schema_name, f"{schema_name}Dto")


def _ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _quoted_literal(value: Any) -> str:
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return str(value)


def _normalize_union(types: list[str]) -> str:
    seen: list[str] = []
    for item in types:
        if item not in seen:
            seen.append(item)
    return " | ".join(seen) if seen else "unknown"


def _schema_to_ts_type(
    schema: Mapping[str, Any] | None,
    *,
    parent_schema: str,
    property_name: str | None = None,
) -> str:
    if schema is None:
        return "unknown"

    if property_name is not None:
        override = FIELD_TYPE_OVERRIDES.get((parent_schema, property_name))
        if override is not None:
            return override

    ref = schema.get("$ref")
    if isinstance(ref, str):
        return _schema_to_ts_name(_ref_name(ref))

    enum_values = schema.get("enum")
    if isinstance(enum_values, list) and enum_values:
        return _normalize_union([_quoted_literal(item) for item in enum_values])

    any_of = schema.get("anyOf")
    if isinstance(any_of, list) and any_of:
        return _normalize_union(
            [
                "null"
                if item.get("type") == "null"
                else _schema_to_ts_type(
                    item,
                    parent_schema=parent_schema,
                    property_name=property_name,
                )
                for item in any_of
            ]
        )

    one_of = schema.get("oneOf")
    if isinstance(one_of, list) and one_of:
        return _normalize_union(
            [
                _schema_to_ts_type(
                    item,
                    parent_schema=parent_schema,
                    property_name=property_name,
                )
                for item in one_of
            ]
        )

    schema_type = schema.get("type")
    if schema_type == "array":
        items = schema.get("items")
        item_type = _schema_to_ts_type(
            items if isinstance(items, Mapping) else None,
            parent_schema=parent_schema,
            property_name=property_name,
        )
        if " | " in item_type:
            return f"({item_type})[]"
        return f"{item_type}[]"

    if schema_type == "object":
        properties = schema.get("properties")
        if isinstance(properties, Mapping) and properties:
            required = set(schema.get("required", []))
            members: list[str] = []
            for key, value in properties.items():
                optional = "?" if key not in required else ""
                member_type = _schema_to_ts_type(
                    value,
                    parent_schema=parent_schema,
                    property_name=key,
                )
                members.append(f"{key}{optional}: {member_type};")
            return "{ " + " ".join(members) + " }"

        additional = schema.get("additionalProperties")
        if additional is True:
            return "Record<string, unknown>"
        if isinstance(additional, Mapping):
            value_type = _schema_to_ts_type(
                additional,
                parent_schema=parent_schema,
                property_name=property_name,
            )
            return f"Record<string, {value_type}>"
        return "Record<string, unknown>"

    if schema_type == "integer" or schema_type == "number":
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "string":
        return "string"
    if schema_type == "null":
        return "null"

    return "unknown"


def _emit_interface(schema_name: str, schema: Mapping[str, Any]) -> str:
    ts_name = _schema_to_ts_name(schema_name)
    properties = schema.get("properties")
    if not isinstance(properties, Mapping):
        raise RuntimeError(f"{schema_name} is not an object schema.")

    required = set(schema.get("required", []))
    lines = [f"export interface {ts_name} {{"]
    for property_name, property_schema in properties.items():
        optional = "?" if property_name not in required else ""
        property_type = _schema_to_ts_type(
            property_schema if isinstance(property_schema, Mapping) else None,
            parent_schema=schema_name,
            property_name=property_name,
        )
        lines.append(f"  {property_name}{optional}: {property_type};")
    lines.append("}")
    return "\n".join(lines)


def _render_contracts(schemas: Mapping[str, Any]) -> str:
    blocks = [SUPPLEMENTAL_TYPES.rstrip()]
    for schema_name in TARGET_SCHEMAS:
        schema = schemas[schema_name]
        blocks.append(_emit_interface(schema_name, schema))
    return GENERATED_HEADER + "\n\n".join(blocks) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate backend-owned UI contract types."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the generated UI contracts would change.",
    )
    args = parser.parse_args()

    schemas = _load_openapi_schemas()
    _assert_target_schemas_exist(schemas)
    rendered = _render_contracts(schemas)

    if args.check:
        current = OUTPUT_PATH.read_text(encoding="utf-8")
        if current != rendered:
            raise SystemExit(
                "Generated UI contracts are out of date. Run "
                "python scripts/generate_ui_contracts.py to refresh them."
            )
        return

    OUTPUT_PATH.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()
