"""
routers/activations.py
======================

Activation Reports API Router
------------------------------

This module provides REST API endpoints for accessing activation report
data generated by the executor's Playwright automation. Reports are JSON
files stored in the output/ directory.

Endpoints:
    GET /api/activations          - List all available activation reports
    GET /api/activations/latest   - Get the most recent activation report
    GET /api/activations/{name}   - Get a specific activation report by filename
"""

import json
from pathlib import Path
from typing import Any

from fastapi import APIRouter, HTTPException

from core.config import settings

router = APIRouter(prefix="/api", tags=["activations"])


def _get_output_dir() -> Path:
    """Return the output directory path from settings."""
    return Path(settings.project.OUTPUT_DIR)


def _list_report_files() -> list[Path]:
    """
    List all JSON report files in the output directory, sorted by
    modification time (newest first).
    """
    output_dir = _get_output_dir()
    if not output_dir.exists():
        return []
    files = sorted(
        output_dir.glob("*.json"),
        key=lambda f: f.stat().st_mtime,
        reverse=True,
    )
    return files


def _read_report(path: Path) -> dict[str, Any]:
    """Read and parse a JSON report file."""
    try:
        with open(path, encoding="utf-8") as f:
            data: dict[str, Any] = json.load(f)
        return data
    except (json.JSONDecodeError, OSError) as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to read report file: {path.name} — {e}",
        ) from e


# =============================================================================
# Endpoints
# =============================================================================


@router.get("/activations")
def list_activations() -> list[dict[str, Any]]:
    """
    List all available activation report files.

    Returns metadata for each report file (filename, size, modified date).
    Reports are sorted by modification time, newest first.
    """
    files = _list_report_files()
    results: list[dict[str, Any]] = []
    for f in files:
        stat = f.stat()
        results.append(
            {
                "filename": f.name,
                "size_bytes": stat.st_size,
                "modified": stat.st_mtime,
            }
        )
    return results


@router.get("/activations/latest")
def get_latest_activation() -> dict[str, Any]:
    """
    Get the most recent activation report.

    Returns the full contents of the newest JSON report file.
    Raises 404 if no reports exist.
    """
    files = _list_report_files()
    if not files:
        raise HTTPException(
            status_code=404,
            detail="No activation reports found in output directory.",
        )
    report = _read_report(files[0])
    report["_metadata"] = {"filename": files[0].name}
    return report


@router.get("/activations/{name}")
def get_activation_by_name(name: str) -> dict[str, Any]:
    """
    Get a specific activation report by filename.

    Args:
        name: The filename of the report (e.g., "activation_report.json")

    Returns:
        Full contents of the requested report file.

    Raises:
        404: If the specified report file does not exist.
    """
    # Prevent directory traversal
    if ".." in name or "/" in name or "\\" in name:
        raise HTTPException(status_code=400, detail="Invalid filename.")

    path = _get_output_dir() / name
    if not path.exists() or not path.is_file():
        raise HTTPException(
            status_code=404,
            detail=f"Report not found: {name}",
        )
    report = _read_report(path)
    report["_metadata"] = {"filename": name}
    return report
