/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        canvasDeep: "#0b0e10",
        canvas: "#101416",
        panel: "#151b1f",
        panelAlt: "#1a2126",
        surface: "#232c34",
        surfaceRaised: "#2a3540",
        lineSoft: "#20282f",
        line: "#2b3640",
        lineStrong: "#3b4a56",
        ink: "#f4f0e8",
        inkSoft: "#d9d2c5",
        mute: "#a19a8b",
        accent: "#9ec6b3",
        accentStrong: "#b6dbc8",
        accentSoft: "#e1f0e8",
        success: "#7bc47f",
        warning: "#d3a35f",
        danger: "#d9776b",
        cyan: "#9ec6b3",
        lime: "#7bc47f",
        amber: "#d3a35f",
        rose: "#d9776b",

        paper: "#0a0a0a",
        paper2: "#141414",
        paper3: "#1c1c1c",
        card: "#0f0f0f",
        bone: "#d6d4d0",
        bone2: "#c5c2bd",
        coral: "#ff5c42",
        coralDeep: "#e84a31",
        coralSoft: "#ffe4dd",
        inkV3: "#f4f1ea",
        inkV3Soft: "#cfcbc2",
        inkV3Mute: "#8a8780",
        inkV3Faint: "#5a5750",
        rule: "#2b2b2b",
        rule2: "#3a3a3a",
        okV3: "#7ab088",
        okBg: "#13231a",
        warnV3: "#d4a85a",
        warnBg: "#2a200f",
        dangerV3: "#ff5c42",
        dangerBg: "#2a1612",
      },
      fontFamily: {
        display: ["Manrope", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      boxShadow: {
        soft: "0 18px 44px rgba(2, 8, 20, 0.28)",
        inset: "inset 0 1px 0 rgba(255, 255, 255, 0.05)",
        focus: "0 0 0 4px rgba(103, 164, 255, 0.18)",
        focusCoral: "0 0 0 2px rgba(255, 92, 66, 0.6)",
      },
      letterSpacing: {
        data: "0.18em",
        eyebrow: "0.18em",
        tab: "0.1em",
        mono: "0.04em",
        display: "-0.045em",
        section: "-0.025em",
        metric: "-0.04em",
      },
      keyframes: {
        pageReveal: {
          from: { opacity: "0", transform: "translateY(4px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        flowDash: {
          to: { strokeDashoffset: "-24" },
        },
        nodePulse: {
          "0%, 100%": { r: "4", opacity: "1" },
          "50%": { r: "5.5", opacity: "0.75" },
        },
        haloPulse: {
          "0%": { r: "6", opacity: "0.6" },
          "100%": { r: "16", opacity: "0" },
        },
        radarSweep: {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        radarBreath: {
          "0%, 100%": { opacity: "0.55" },
          "50%": { opacity: "0.85" },
        },
        tlPulse: {
          "0%": { r: "4.5", opacity: "0.9" },
          "100%": { r: "16", opacity: "0" },
        },
        laneSlide: {
          from: { opacity: "0", transform: "translateX(-8px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
      },
      animation: {
        pageReveal: "pageReveal 280ms ease-out both",
        flowDash: "flowDash 2.4s linear infinite",
        flowDashFast: "flowDash 1.4s linear infinite",
        nodePulse: "nodePulse 2.2s ease-in-out infinite",
        haloPulse: "haloPulse 2.2s ease-out infinite",
        radarSweep: "radarSweep 8s linear infinite",
        radarBreath: "radarBreath 4s ease-in-out infinite",
        tlPulse: "tlPulse 2.4s ease-out infinite",
        laneSlide: "laneSlide 500ms cubic-bezier(0.2, 0.8, 0.2, 1) both",
      },
    },
  },
  plugins: [],
};
